### ISSUE TITLE
[FEAT] Boolean to disable page scrolling

### ISSUE THREAD

**Issue by luisliz** [fermoya/SwiftUIPager#103]
**Is your feature request related to a problem? Please describe.**
I'm using navigationview while working with the pager and when I'm using a navigation I can scroll past it and I don't want it to.  

**Describe the solution you'd like**
A boolean binding variable that I can switch back and forth. 

**Additional context**
I modified a version of this and it can be done but I would like it on the official package that way I don't have to use an outdated package. I can create a fork of my proposed solution.

**Comment by fermoya** [comment]
Hi @luisliz , have you tried using `allowsDragging` modifier? 

Also, when combining gestures (or views that are touchable, like `NavigationLink`) you might be interested in `pagingPriority(.simultaneous)`.

**Comment by luisliz** [comment]
Oh, that's exactly what I wanted! I was thinking of something with the disabled boolean. 

Thank you very much for the help and for the plugin. I love it!

**Comment by fermoya** [comment]
Thanks for the kind words.

I’m closing this issue then. Feel free to open a new issue if you find any issue
