### ISSUE TITLE
[FEAT] Scroll to Top functionality, similar to ScrollView

### ISSUE THREAD

**Issue by JetPlaneJJ** [fermoya/SwiftUIPager#117]
**Is your feature request related to a problem? Please describe.**
This feature is not related to a problem I currently have, but it would be nice to have a "scroll to top" animation similar to the way ScrollView scrolls to the top upon tapping the status bar/notch. 

**Describe the solution you'd like**
Ability to scroll back or go back to the top page after tapping the notch/status bar/top if currently not at the top page. Ideally there could be an animation of "scrolling" like ScrollView's scrollToTop.

**Describe alternatives you've considered**
I have looked online at how other people are doing "scroll to top", but they are all ScrollViews or UITableViews. My current workaround is to have people tap a button on the bottom to return to the top page instantly (no animation, just setting current page index to 0).

**Comment by fermoya** [comment]
I’m going to close this as I don’t think it could be implemented in the way it’s described. Feel free to reopen if any new ideas
