### ISSUE TITLE
[REQUEST] Enable.disable scrolling programatically

### ISSUE THREAD

**Issue by skywalkerdude** [fermoya/SwiftUIPager#130]
**Is your feature request related to a problem? Please describe.**
I would like to enable/disable scrolling programatically

**Describe the solution you'd like**
Add a `.shouldScroll(bool)` modifier to `Pager` Where we can disable/enable scrolling

**Comment by fermoya** [comment]
hi @skywalkerdude , have you tried `allowsDragging`?
