### ISSUE TITLE
Populate from CoreData FetchRequest

### ISSUE THREAD

**Issue by lsaunders80** [fermoya/SwiftUIPager#140]
Hi, couldn't see anywhere else to ask this.. just wondering if it's possible to use a fetch request result as the data for the pager?

I currently have:
```
@FetchRequest(entity: Order.entity(), sortDescriptors: [])

var orders: FetchedResults<Order>
```
I tried setting the Pager.data parameter to orders, but that didn't work.

**Comment by fermoya** [comment]
Hi, `Pager` expects an `Array` of `Equatable` elements and a `keyPath` to an identifier. `FetchedResults` is a `RandomAccessCollection`

**Comment by fermoya** [comment]
@lsaunders80 , just use `Array(orders)` and make sure that either `Order` conforms to `Identifiable` or you pass a `keyPath` to an identifier:
```swift
struct Order {
    id: String
   // more variables
}

@State var page = 0

let pager = Pager(page: $page, data: Array(orders), id: \.id) {
    // your view
}
```

**Comment by fermoya** [comment]
As part of #135 , version [1.13.0-beta.1](https://github.com/fermoya/SwiftUIPager/releases/tag/1.13.0-beta.1) supports an initializer that takes any `RandomAccessCollection` so you can pass your `orders` collection directly now:

```swift
struct Order {
    id: String
   // more variables
}

@State var page = 0

let pager = Pager(page: $page, data: orders, id: \.id) {
    // your view
}
```
