### ISSUE TITLE
If the pager view has padding and cornerRadius and use .interactive, the UI breaks

### ISSUE THREAD

**Issue by NeverwinterMoon** [fermoya/SwiftUIPager#15]
```swift
Pager(data: dataList) { data in
   VStack(alignment: .leading, spacing: 0) {
      Text(data.text).foregroundColor(.white)
    }
    .padding()
    .background(Color.red)
    .cornerRadius(4)    
}
```

Before scrolling between pages, everything looks fine. After any scroll, the text becomes covered by the background colour. If either `padding` or `cornerRadius` is removed, it works fine.

**Comment by fermoya** [comment]
Hi @NeverwinterMoon ,

First of all, thanks a lot for your feedback. Could you please tell me what version of Xcode are you using? Also, the command line in tools in Xcode -> Preferences -> Locations -> Command Line Tools ? 

I think it might have to do with the Xcode version. This is my code:
```
    var body: some View {
        Pager(data: Array(0..<10),
              id: \.self) { index in
                VStack(alignment: .leading, spacing: 0) {
                    Text("Page: \(index)").foregroundColor(.white)
                }
                .padding()
                .background(Color.red)
                .cornerRadius(4)
                .shadow(radius: 5)
        }
        .interactive(0.6)
        .itemSpacing(10)
        .itemAspectRatio(0.8)
        .padding(8)
        .background(Color.gray.opacity(0.2))
    }
```
And this is my result:
![simulator](https://user-images.githubusercontent.com/11335612/75281282-e6982480-5806-11ea-9c09-90dcb324cc83.gif)

Fernando

**Comment by NeverwinterMoon** [comment]
Xcode version is 11.3.1 (11C504) and so are the Command Line Tools.

https://gyazo.com/5fb0d1347d135f1837f74ea3162fe32a

**Comment by fermoya** [comment]
Hi @NeverwinterMoon ,

Try adding `.shadow(radius: 0)` to your `bannerView` after `cornerRadius` and see if that works for you. It is working for me.

I believe this a SwiftUI issue as the problem appears when combining different view modifiers. I'll keep an eye on it, tho.

Thanks

**Comment by NeverwinterMoon** [comment]
Ah, indeed. `.shadow(radius: 0)` fixes the issue. Thanks!
