### ISSUE TITLE
Animation between pages a stiff

### ISSUE THREAD

**Issue by iansilber** [fermoya/SwiftUIPager#156]
When swiping between pages, the curve that's being used feels a tad stiff (almost linear). A good comparison is the the Photos app that has a smooth easing in/out. Would be nice to follow the default iOS patterns or be able to configure this.

**Comment by fermoya** [comment]
Hi @iansilber , the library uses `.easeOut` for transitions but this can be changed by using `pagingAnimation` . `.standard` equals `.easeOut` and `.steep` is a custom Bézier curve used for `.multiplePagination()`. You can try using `.pagingAnination(.custom(.easeInOut))`

**Comment by fermoya** [comment]
I just checked and I don’t have it documented, apologies for that. Will add it soon

**Comment by iansilber** [comment]
Thanks for the info! I tried `.pagingAnimation(.custom(.easeInOut))` but get the error `Cannot infer contextual base in reference to member 'easeInOut'`

**Comment by fermoya** [comment]
Hi, @iansilber , apologies. It would be:
```swift
Pager(...)
    .pagingAnimation({ _, _, _, _ in
        return PagingAnimation.custom(animation: .easeInOut)
    })
```

**Comment by iansilber** [comment]
that worked, thanks!

**Comment by fermoya** [comment]
I'm going to close this issue then @iansilber . Sorry again I gave you a wrong snippet. Sometimes I try to come back to you ASAP and give a prompt answer from my phone

**Comment by fermoya** [comment]
I've added this to the `README` :)
