### ISSUE TITLE
[FEAT] Add paging dots (PageIndexView) to replicate TabView with TabPageViewStyle

### ISSUE THREAD

**Issue by quidnu** [fermoya/SwiftUIPager#169]
It would be nice to have an option to show page index dots/pips like TabView with TabPageViewStyle.

**Comment by fermoya** [comment]
Hi @quidnu , this specific to each scenario and would complicate this library. You can easily use `Pager` and use `disableDragging` to show a `Pager` which whose page content is a `Circle`. Then, just link the pages:
```
ZStack {
  Pager(page: $page, ...) // your content to display
  Pager(page: $page, // passing the same binding will make it move at the same time
             data: myData.enumerated.map { $0.offset }, // use same data you pass to your the other `Pager`, just use the index
             id: \.self) {
      Circle()
        .fill($0 == page ? Color.white : Color.gray)  // different color for the dot on focus
  }
  .preferredItemSize(CGSize(width: 20, height: 20))
  .disableDragging()
  .frame(CGSize(width: 150, height: 40))
  .offset(// position wherever you wish)
}

**Comment by X901** [comment]
> Hi @quidnu , this is specific to each project and would complicate this library (position, color, more modifiers to maintain, ...).
> 
> You can easily use another `Pager` to achieve what you describe by using `disableDragging` on a `Pager` whose page content is a `Circle`. Then, just link the pages:
> 
> ```
> ZStack {
>   Pager(page: $page, ...) // your content to display
>   Pager(page: $page, // passing the same binding will make it move at the same time
>              data: myData.enumerated.map { $0.offset }, // use same data you pass to your the other `Pager`, just use the index
>              id: \.self) {
>       Circle()
>         .fill($0 == page ? Color.white : Color.gray)  // different color for the dot on focus
>   }
>   .preferredItemSize(CGSize(width: 20, height: 20))
>   .disableDragging()
>   .frame(CGSize(width: 150, height: 40))
>   .offset(// position wherever you wish)
> }
> ```
> 
> This isn’t something out of the scope of the library. If it isn’t clear, I can add this to one of the examples

Could you please update the demo ?
I tried your code with your example I faced issues

**Comment by peterz** [comment]
You don't need another Pager to achieve that.

    HStack(spacing: 5) {
        ForEach(pages.indices) { idx in
            Circle()
                .fill(idx == page ? Color.lightBlue : Color.gray)
                .frame(width: 6, height: 6)
        }
    }.frame(height: 20)
