### ISSUE TITLE
[BUG] Strange behavior with nested Pagers

### ISSUE THREAD

**Issue by metsfan** [fermoya/SwiftUIPager#170]
**Describe the bug**
I am experiencing a strange behavior trying to use nested pagers, with an outer horizontal pager and an inner vertical pager on each page. The outer pager works totally fine. The inner vertical pagers appears to change pages, but the animation looks very strange, and it does not behave 100% correctly in all cases. On this one unfortunately I have no idea what the issue is. Hopefully its an error in my configuration.

**To Reproduce**
This code will reproduce the issue.

```
struct ContentView: View {
    @State var outerPage: Int = 0
    @State var innerPages: [Int] = [0, 0, 0]
    
    var body: some View {
        ZStack {
            Pager(page: $outerPage, data: Array(0..<3)) { parent in
                Pager(page: $innerPages[parent], data: Array(0..<10)) { item in
                    ZStack {
                        Color.red
                        Text("\(parent)_\(item)")
                            .foregroundColor(.white)
                    }
                }
                .vertical()
                .pagingPriority(.simultaneous)
            }
            .pagingPriority(.simultaneous)
        }
    }
}
```

**Expected behavior**
I would expect that each of the internal pagers behave correctly as a vertical pager

**Screenshots / Videos**
The behavior will be very easily observed using the above code sample

**Environment:**
 - OSX: [e.g. iOS] iOS 14.2
 - Device [e.g. iPhone6] iPhone 7
- SwiftUIPager version 1.14.1

**Additional context**

**Comment by fermoya** [comment]
Hi @metsfan , I'm gonna tell you the whole story and maybe you can help with this one. I changed `page` from being a simple `Binding` to an `ObservedObject`. Reason is I found that for some reason the views were being updated in two steps:
* First the `State` variables
* Then the `Binding`
This didn't happen with an `ObservedObject`. You can find more info [here](https://developer.apple.com/forums/thread/667988) and [here](https://developer.apple.com/forums/thread/667720). You can maybe try with version `1.13.0` and see if it works better and ping me here. 

I've tested your code and I've managed to make it work by changing `ObservedObject` to `StateObject` ([line 150](https://github.com/fermoya/SwiftUIPager/blob/2e3b56609a82c9eaf7c8c8ddc20ef62882c8e6b2/Sources/SwiftUIPager/PagerContent.swift#L150)  in `PagerContent`)

**Comment by fermoya** [comment]
@metsfan I've released [1.14.2-beta.1](https://github.com/fermoya/SwiftUIPager/releases/tag/1.14.2-beta.1) that should fix this problem on `iOS 14`. Unfortunately, the problem still exists on `iOS 13`.

**Comment by metsfan** [comment]
@fermoya Your update in 1.14.2-beta1 appears to have solved the issue entirely. I think changing to `StateObject` seems to have solved the problem. Thankfully I'm targeting iOS 14 so it's not an issue for me. Given that iOS 14 adoption is already over 70% it's probably fine.

**Comment by metsfan** [comment]
@fermoya the only bug I'm seeing now is that the `onPageChanged` callback is not being called.

**Comment by fermoya** [comment]
@metsfan it might not be so direct as I'd expected. I'll need to dive deeper into this. For now, I would suggest using version `1.13.0`. That one is using a `Binding` and should work fine

**Comment by metsfan** [comment]
Ok thanks

**Comment by quidnu** [comment]
>  it might not be so direct as I'd expected. I'll need to dig deeper into this. For now, I would suggest using version `1.13.0`. That one is using a `Binding` and should work fine

The change seems to break onPageChanged handler for me, it stops getting called after the first or second call.

**Comment by fermoya** [comment]
I've made a new beta [1.14.2-beta.2](https://github.com/fermoya/SwiftUIPager/releases/tag/1.14.2-beta.2). Please, use the new initializer I've made available and let me know if you find any other issue:
```
struct ContentView: View {
    @StateObject var outerPage = PagerModel(page: 0)
    @State var innerPages: [PagerModel] = [
        PagerModel(page: 0),
        PagerModel(page: 0),
        PagerModel(page: 0)
    ]
    
    var body: some View {
        ZStack {
            Pager(page: outerPage, data: Array(0..<3)) { parent in
                Pager(page: innerPages[parent], data: Array(0..<10)) { item in
                    ZStack {
                        Color.red
                        Text("\(parent)_\(item)")
                            .foregroundColor(.white)
                    }
                }
                .vertical()
                .pagingPriority(.simultaneous)
            }
            .pagingPriority(.simultaneous)
        }
    }
}

extension Int: Identifiable {
    public var id: Int {
        self
    }
}
```

**Comment by fermoya** [comment]
Should be solves now, please use release 2.0.0
