### ISSUE TITLE
[QUESTION] Pass Int as page index

### ISSUE THREAD

**Issue by skegget** [fermoya/SwiftUIPager#180]
Hi,

first of all, fantastic paging component! Second, I'm a SwiftUI beginner, so please bare with me :)

I have this app project where the weeks of the current year plays a central role. Each view represents one week and the users can swipe between weeks or select a single week which then will be presented in the page viewer. I have been following the SwiftUIPager instructions and a simplified example of my setup looks like this (basically like the instructions):

```
import SwiftUIPager

struct ContentView: View {
    @StateObject var page: Page = .withIndex(someValue)

    var body: some View {
        Pager(page: page,
                          data: items,
                          id: \.self,
                          content: { index in
                            //... some code
        })
    }
}
```

Since my page index always corresponds to the users selected week I'm wondering if it's possible to replace _@StateObject var page: Page = .withIndex(someValue)_ with something like _@State var pageIndex = someValue_? And then use pageIndex in Pager, like:

Pager(page: $pageIndex, data: ...

Or, as in my case. Use the already defined selected week value (Int) as page index? 

I have tried this but I'm getting a warning saying: "Cannot convert value of type 'Binding<Int>' to expected argument type 'Page'.

Thanks!

**Comment by fermoya** [comment]
@skegget why do you want it to be a `Binding`? What's the problem with defining it as `StateObject`? `Pager` used to take a `Binding` back then but that changed recently as it gave more control over the view update. Long story short, `Pager` was using several `State` variables along with this `Binding` so wrapping all this into an `ObservableObject` was a better solution.

**Comment by skegget** [comment]
Hi!
I have been thinking about what you said and I'm about to do some changes to my code. But I have some additional questions. And again, I'm a beginner so I might have gotten this all wrong.

As I mentioned above, my app I centered around weeks. Today I have a separate @Published variable for the 'selectedWeek' but I'm thinking that I might as well use the page number to keep it clean (one page = one week). The thing is that I want to react on page changes, in other words when the user swipes and selects another page (week). When this happens I want to trigger functions in a custom ObservableObject class. But I don't really know how to actually get notified on any page change base on the same instance.

I hope this makes any sense. Thanks!

**Comment by fermoya** [comment]
Hi @skegget . You can use `onPageChanged` or `onPageWillChange` modifiers on `Pager` to get notified on page index changes and execute any method you need in your `ObservableObject`.

If you need to refresh a view when the page changes, you can use `page.index` directly and `SwiftUI` will take care of everything. 

You can see all these scenarios in the sample project

**Comment by skegget** [comment]
Sorry, forgot to reply on this! Many thanks for your help!
