### ISSUE TITLE
[BUG] Cannot find type 'Page' in scope

### ISSUE THREAD

**Issue by umwelt** [fermoya/SwiftUIPager#181]
Xcode 12.3
Installed via CocoaPods 

Cannot find type 'Page' in scope

Im using the example provided, I added the error points Im seeing
Any idea where Im wrong?

```
@StateObject var page: Page = .first() //  <- Cannot find type 'Page' in scope
// @ObservedObject var page: Page = .first()
var items = Array(0..<10)

var body: some View {
    Pager(page: page,
          data: items,
          id: \.identifier, // <- value of type Int has no member identifier
          content: { index in
              // create a page based on the data passed
              Text("Page: \(index)")
     })
 }

```

**Comment by fermoya** [comment]
@umwelt what `SwiftUIPager` version are you using? This is available in version `2.0.0`. I just created a quick Test project and it's all good.

If you open `Test.xcworkspace` you'll see it compiles just fine.
[Test.zip](https://github.com/fermoya/SwiftUIPager/files/5841373/Test.zip)

**Comment by umwelt** [comment]
thanks for the example.
pod 'SwiftUIPager' installed version -> 1.14.1

But indeed version 2.0  solves that issue.

always on following the same example on the docs, Im seeing this error -> Value of type Int has no member identifier on the id

```
  Pager(page: page,
              data: items,
              id: \.identifier, // Value of type Int has no member identifier
              content: { index in
                  // create a page based on the data passed
                  Text("Page: \(index)")
         })
```

**Comment by fermoya** [comment]
You need to use `\.self` or do;
```
extension Int: Identifiable {
  var identifier: Int { self }
}
```
And use `init(page:data:content:)` instead.

I'd suggest to take a look at the [Example project](https://github.com/fermoya/SwiftUIPager/tree/develop/Example) in the repo.
