### ISSUE TITLE
onPageChanged only called when user swipes to a new page

### ISSUE THREAD

**Issue by DominikButz** [fermoya/SwiftUIPager#182]
**Describe the bug**
I use two buttons (up and down) to switch to another page. Additionally the user can swipe. But onPageChanged is only called when swiping. 

**To Reproduce**
I use this code for the buttons: 
            VStack(spacing: 15) {
                Button {
                    if self.page.index > 0 {
                      
                        self.page.update(.previous)
                    }
                } label: {
                    Image(systemName: "chevron.up")
                }.disabled(self.page.index <= 0)

                Button {
                    if self.page.index + 1 < self.months.count {
                        self.page.update(.next)
               
                    }
                } label: {
                    Image(systemName: "chevron.down")
                }.disabled(self.page.index + 1 >= self.months.count)
            
            }.font(.system(size: 25)).padding(.top, 40).padding(.horizontal, 10)

**Expected behavior**
I expected that the onPageChanged closure is also called when updating the page directly e.g. through self.page.update(.next). Please let me know if the behaviour is intentional. 

**Screenshots / Videos**

**Environment:**
iOS 14.4

**Comment by fermoya** [comment]
Hi @DominikButz , this is expected and it's not a BUG. `Pager` can only detect when a page will and did change if the user is swiping. It can detect when a user manually did change a page but this would be misleading with `onPageWillChange` callback. 

Perhaps I can specify this better in the docs, but as I said this is intentional

**Comment by DominikButz** [comment]
Thanks - yes, you are right. It makes sense because if the index is changed in code, I don't need to detect the change any more.
