### ISSUE TITLE
[QUESTION] Slow down animation

### ISSUE THREAD

**Issue by skegget** [fermoya/SwiftUIPager#183]
Is it possible to slow down the animation that kicks in once a page is dragged and then released? I came across .pagingAnimation and velocity in the instructions but I'm not sure this is the way to go.

If it is, would you mind giving me a real example of how to implement it? I can't seem to figure out how to use it from the instructions.

Many thanks!

**Comment by fermoya** [comment]
If you see [the documentation](https://github.com/fermoya/SwiftUIPager/blob/develop/Documentation/Usage.md#page-transitions), you can implement `.pagingAnimation(_:)` as you mention:
```
Pager(...)
    .pagingAnimation({ currentPage, nextPage, totalShift, velocity in
        return PagingAnimation.custom(animation: .easeInOut)
    })
```
By default, `Pager` uses `PagingAnimation.standard` which is `Animation.easeOut(duration: 0.35)`. If you need to slow it down, you can return `.standard(animationDuration)`. If `.easeOut` is not the right animation for you, please return `.custom(animation: myCustomAnimationCurve)`. You can also use the callback argument to choose different animations depending on the current page, next page, dragging offset and  dragging velocity. For instance:
```
Pager(...)
    .pagingAnimation({ currentPage, nextPage, totalShift, velocity in
        guard abs(nextPage - currentPage) > 1 else { return .standard(1) }
        return PagingAnimation.custom(animation: .steep(0.3))
    })
```

**Comment by skegget** [comment]
Great, thanks!
