### ISSUE TITLE
Cannot assign to property: 'page' is a get-only property [FEAT]

### ISSUE THREAD

**Issue by konrain** [fermoya/SwiftUIPager#184]
**Describe the bug**

I'm trying to always start the Pager in the middle, but page being a @StateObject, it can't be changed? in the init or onAppear

**Comment by fermoya** [comment]
@konrain you can initialize a `Page` by using `firstPage()` or `withIndex(_:)` convenience methods.

Please, take a look at the Sample project and the Swift docs on `Page`. To manually move to another page, call `update(_:)` on your `Page` instance like it's done on [ColorsExampleView](Example/SwiftUIPagerExample/Examples/ColorsExampleView.swift) or directly change its property `index` as done in [InfiniteExampleView](Example/SwiftUIPagerExample/Examples/InfiniteExampleView). Use one way or another depending on your needs and whether you need to trigger a SwiftUI update or control it yourself.
For most scenarios, you'll want to use `update(_:)`.

**Comment by konrain** [comment]
thanks @fermonya, but maybe there is a misunderstanding? I'm aware of all those, I wanted to start the Pager in the center item.

for example: 

```swift
  var items: [String]
  @StateObject var page: Page = Page.first()
  init() {
     // Here
     self.page = Page.withIndex(items.count / 2)
  }
  var body: some View {
    Pager(page: page, data: items, id: \.self) {  _ in
      Text("Item")
    }
   // Or Here
   .onAppear { page = items.count / 2
}
```

**Comment by fermoya** [comment]
@konrain declare your `page` by using `withIndex`:
```swift
  @StateObject var page: Page = .withIndex(items.count/2)
```

**Comment by konrain** [comment]
@fermoya thanks but thats not possible because self is not available yet...

**Comment by fermoya** [comment]
@konrain you need to initialize the `StateObject` in an `init`:
```swift
var items: [String]
@StateObject var page: Page

init(items: [String]) {
  self._page = StateObject(wrappedValue: .withIndex(items.count/2)
  self.items = items
}
```
Your problem here is how to initialize `StateObject` in an initializer. You need to prefix the variable name with an underscore "_"
