### ISSUE TITLE
How to select different page when Pager already presenting

### ISSUE THREAD

**Issue by ramunasjurgilas** [fermoya/SwiftUIPager#19]
I need to select different page when user clicks on the map pin annotation. I do not see the way how to do it. How I could swipe to different page programmatically? 

```
    var body: some View {
        Pager(data: mapViewModel.provider.items) { item in
            VStack {
                Text("OHO")
            }
        }
        .onPageChanged({ self.mapViewModel.selectPinAt(index: $0) })
        .firstPage(mapViewModel.selectedItemIndexSubject.value ?? 0)
        .itemSpacing(10)
        .itemAspectRatio(0.85, alignment: .end)
    }
```

**Comment by fermoya** [comment]
Use version 1.3.1. I've changed a state variable to a binding so that you can programatically move it. See the example [here](https://github.com/fermoya/SwiftUIPager/blob/master/Example/SwiftUIPagerExample/Examples/ColorsExampleView.swift) an example of how to use it.

**Comment by ramunasjurgilas** [comment]
Thanks for quick fix and release!
