### ISSUE TITLE
Apply opacity to non focused Items 

### ISSUE THREAD

**Issue by umwelt** [fermoya/SwiftUIPager#190]
**Describe the solution you'd like**
Similar to 
.interactive() or rotation3D()

Can you hint me at what level will you create this type of behaviour?

**Comment by fermoya** [comment]
@umwelt , I'd do that by taking into account the page index. So you have your `Pager`:
```swift
@StateObject var currentPage: Page = .first()

var body: some View {
  Pager(...) { index in
    // return a page here based on index
  }
}
```
You can compare the callback `index`  to your `Page.index` and apply some opacity:
```swift
Pager(...) { index in
  MyPage(index: index)
    .opacity(opacity(at: index))
}
```
and then
```swift
/// Decrements proportionally the opacity by 0.2 if unfocused
func opacity(at index: Int) -> Double {
  let value = 1 - abs(Double(index - page.index)) * 0.2 
  return max(0, min(1, value))
}
```
Does that make sense?

**Comment by umwelt** [comment]
@fermoya
Thanks, yes this really helps.
If I can add something is that, compared to the other methods, specially "rotation3D()" this will miss the progressiveness of the effect -> drag coordination.
But for me this works, thanks for the expedite help!

**Comment by fermoya** [comment]
@umwelt I know you were happy with my answer but I liked the idea of implementing this if you're interested.

I haven't still decided on a name for the modifier, for now I've chosen `faded(_:)` but I think I'll deprecate the current `interactive(_:)` in favor of `interactive(scale:)` and use `interactive(opacity:)` instead.

Let me know if you have any suggestions. See it in action [here](https://github.com/fermoya/SwiftUIPager/blob/fix/ios13-issues/):
https://github.com/fermoya/SwiftUIPager/blob/fix/ios13-issues/

**Comment by umwelt** [comment]
@fermoya 
nice, I also agree that extending the interactive modifier to allow opacity feels more natural, based on the current implementation of the Pager.
The links above are broken

**Comment by fermoya** [comment]
@umwelt update the links

**Comment by umwelt** [comment]
@fermoya 
that looks perfect to me.
are you going to release it on cocoa pods anytime soon?

**Comment by fermoya** [comment]
I have a PR ready to go, I’d be releasing a beta first. I might deal with
some other issue before making an official release.

Over the weekend I’ll release `2.1.0-beta.1`

**Comment by fermoya** [comment]
[`2.1.0-beta.1`](https://github.com/fermoya/SwiftUIPager/releases/tag/2.1.0-beta.1). You might see more betas coming up over the weekend but it’s not something relevant, just fixes to a new CI/CD workflow. Once a beta is set-up I can’t stop generating new ones till I make an official release 😅

**Comment by umwelt** [comment]
@fermoya 
thanks for the hard work!
the new interactive with opacity works perfect!
Also unrelated to this item, the fix you did on the not animate while transitioning gave the gesture that bit of resistance that was needed, I was dealing with some pages skipped on fast drag velocities, but now looks and feels just awesome.

**Comment by fermoya** [comment]
Thanks for your feedback @umwelt , I appreciate it. I’ll let you know when I make an official release 👍

**Comment by fermoya** [comment]
[`2.1.0`](https://github.com/fermoya/SwiftUIPager/releases/tag/2.1.0) is live @umwelt
