### ISSUE TITLE
Does this work with any View?

### ISSUE THREAD

**Issue by transat** [fermoya/SwiftUIPager#195]
The current examples construct the pages dynamically so it's unclear if SwiftUIPager can work with any existing View. If it can, would it be possible to add an example for that? Cheers.

**Comment by fermoya** [comment]
Hi @transat what do you mean exactly? In `SwiftUI` the body of the views is recalculated very often and you're not meant to declare stored views if that's what you mean. Can you please elaborate?

**Comment by transat** [comment]
Hi. I meant is there any potential for this kind of syntax, using any View?

```Pager{ 
    PageOne()
    PageTwo()
}```

Or is this package strictly for paging items of the one type? Cheers.

**Comment by fermoya** [comment]
@transat nope. Currently you'd need to do the following:
```swift
Pager(...) { index in 
  switch index {
    case 0: return PageOne()
    case 1: return PageTwo()
    default: return EmptyView()
  }
}
```

**Comment by transat** [comment]
That's still great! Will try it out. Cheers!

**Comment by transat** [comment]
Ah. But in that case, what would I put where you have the ellipsis?

**Comment by fermoya** [comment]
Do you mean the brackets `(...)`?

**Comment by transat** [comment]
Yes.

**Comment by fermoya** [comment]
See a list of examples here:
https://github.com/fermoya/SwiftUIPager/tree/develop/Example/SwiftUIPagerExample/Examples

And the Basic initialization:
https://github.com/fermoya/SwiftUIPager/blob/develop/Documentation/Usage.md#initialization

```swift
@StateObject var page: Page = .first()
var items = Array(0..<10)

var body: some View {
    Pager(page: page,
          data: items,
          id: \.identifier,
          content: { index in
              // create a page based on the data passed
              Text("Page: \(index)")
     })
 }
```
