### ISSUE TITLE
[BUG] Loading pages on-demand at the start not working correctly on 2.1.0

### ISSUE THREAD

**Issue by bardigolriz** [fermoya/SwiftUIPager#204]
**Describe the bug**
I’ve followed the code in the documentation showing how to load pages on demand at the start:

```
@State var count: Int = -1
@StateObject var page: Page = .first()
// @ObservedObject var page: Page = .first()
@State var data = Array(0..<5)
```

```
Pager(page: self.page,
        data: self.data,
        id: \.self) {
    self.pageView($0)
}
.onPageChanged({ pageIndex in
    guard pageIndex == 1 else { return }
    let newData = (1...5).map { $0 * self.count }
    withAnimation {
        self.data.insert(contentsOf: newData, at: 0)
        self.page.index += 5
        self.count -= 1
    }
})
```

However, the newData that gets created is in the wrong order: -1,-2,-3,-4,-5. No idea if this leads to issues, but a workaround is to add .reversed(). And because we decrement self.count by 1, the next time pages are added to the start they’ll be -10,-8,-6,-4,-2. As a result, I’ve made changes to get data that’s inserted be the correct values in the correct sequence. But, this is actually _not_ the issue. The issue is the page.index moved to is not correct when I add pages to the start. 

**To Reproduce**

To be clear, I’ve made changes to the property values to get the new data items to be appropriately valued/sequenced. Regardless, with or without my changes, the page.index moved to is not correct. However, with my changes, they seem to be closer to the correct index, off by two.

I’ve changed newData to: 
`let newData = (1...5).map { $0 + (count + 1) * -5 }`

And made count start at 0:
`@State private var count: Int = 0`

My data is: 
`@State private var data = Array(1...5)`

And page starts at:
`@StateObject var page: Page = .withIndex(2)`

This is my onPageChanged closure:

```
.onPageChanged { page in
    guard page == 1 else {
        guard page == data.count - 2 else { return }
        guard let last = data.last else { return }
        
        /// adding pages to the end
        let newData = (1...5).map { last + $0 }
        withAnimation {
            data.append(contentsOf: newData)
        }
        return
    }
    
    /// adding pages to the start
    let newData = (1...5).map { $0 + (count + 1) * -5 } 
    withAnimation {
        data.insert(contentsOf: newData, at: 0)
        self.page.index += 5
        count += 1
    }
}
```

I debugged self.page.index’s value after 1) data.insert as well as 2) after it has 5 added to it.

After `data.insert(contentsOf: newData, at: 0)`, it’s index **1**. This makes sense, as it was originally 2 and a swipe right should reduce it by one.

However when I add += 5 to it, its index is being returned as 4 (and not 6 i.e. previous index 1 + 5). This is wrong. So with this data:
[-4, -3, -2, -1, 0, 1, 2, 3, 4, 5]
Its page returned is 0, as opposed to the expected 2.

I breakpointed into the index property setter of Page:

```
    public var index: Int {
        get { _index }
        set { _index = min(totalPages - 1, max(0, newValue)) }
    }
```

I noticed the problem is totalPages is 5 when the index is being set, resulting in min(4,6) returning a 4.

After the index is set, I noticed Pager’s initialiser is called again with its Page’s index set to 4 but for the first time its totalPages is now showing as 10. However, at this point, this correct up-to-date knowledge doesn’t seem to be used.

FWIW I tried `self.page.update(.new(index: self.page.index + 5))` too but this didn’t make a difference.

**Expected behavior**
If totalPages was showing as 10 immediately after 5 new data items were added to the start, then the index would be the expected 6.

Here you can see when new pages are added, it suddenly jumps to the wrong index (February, index 6, to December, index 4):

![RocketSim Recording - iPhone 12 Pro - 2021-03-12 20 16 24](https://user-images.githubusercontent.com/8938930/110993954-f0d48480-836f-11eb-81ec-2a71ed987667.gif)

**Environment:**
 - OSX: iOS 14.4
 - Device iPhone 12 Pro simulator
- SwiftUIPager version 2.1.0

**Comment by fermoya** [comment]
Hi @bardigolriz , the example is just a way to show how to prepend new items on-demand. I don't think this is an issue with the library.

In any case, I've opened this pull-request to address the docs update:
https://github.com/fermoya/SwiftUIPager/pull/205

https://user-images.githubusercontent.com/11335612/111035209-401ec180-8411-11eb-9390-fb66ac117bb1.mov

**Comment by steelegg** [comment]
I also encountered this problem, and I found that it was because my initial data only had 5 entries. In the example 'Infinite Example View', 7 pieces of data were initialized. I changed it to be the same as the example, and after initializing 7 pieces of data, the problem was solved. I think this should be a problem.

**Comment by steelegg** [comment]
@State private var page1: Page = .withIndex(3)

**Comment by steelegg** [comment]
page1 = .withIndex(centerIndex)

**Comment by steelegg** [comment]
> I also encountered this problem, and I found that it was because my initial data only had 5 entries. In the example 'Infinite Example View', 7 pieces of data were initialized. I changed it to be the same as the example, and after initializing 7 pieces of data, the problem was solved. I think this should be a problem.

I tried another way of writing and finally solved the problem. It's really a tricky one

**Comment by steelegg** [comment]
> I also encountered this problem, and I found that it was because my initial data only had 5 entries. In the example 'Infinite Example View', 7 pieces of data were initialized. I changed it to be the same as the example, and after initializing 7 pieces of data, the problem was solved. I think this should be a problem.

I tried another way of writing and finally solved the problem. It's really a tricky one
@State private var page1: Page = .withIndex(3)
When I want to make changes, I directly use 
page1 = .withIndex(3)
