### ISSUE TITLE
[FEAT] Animation when scrolling programmatically

### ISSUE THREAD

**Issue by ln-12** [fermoya/SwiftUIPager#209]
**Is your feature request related to a problem? Please describe.**
When using `page.update(.next)` and `page.update(.previous)`, the page is changed without any animation.

**Describe the solution you'd like**
Animate the page transition.

Is this possible to implement?

**Comment by ln-12** [comment]
For anyone wondering: the solution is to use `withAnimation`:
```
withAnimation {
    page.update(.next)
}
```

**Comment by fermoya** [comment]
Hi @ln-12 , this is intended. It’s up to the user to use the animation the want:
```swift
withAnimation(desiredAnimation) {
  page.update(.next)
}
```
Please check out [ColorsExampleView](https://github.com/fermoya/SwiftUIPager/blob/develop/Example/SwiftUIPagerExample/Examples/ColorsExampleView.swift) inside the example project
