### ISSUE TITLE
Can not swipe throw pages when content on the bottom of the screen

### ISSUE THREAD

**Issue by ramunasjurgilas** [fermoya/SwiftUIPager#21]
Can not swipe throw pages when pager is on the bottom of the screen. It was working with 1.3.0 version, but dose not works with 1.3.1 version.

Code which places pages on the bottom of the screen:
```
    var body: some View {
        Pager(page: $model.selectedPage, data: model.playrooms) { playroom in
            VStack {
                Spacer()
                HStack {
                    Text("Page text on the botton which can not be moved.")
                }
                .background(Color.red)
            }
        }
        .onPageChanged({ self.model.mapViewModel.selectPinAt(index: $0) })
        .itemSpacing(2)
        .itemAspectRatio(0.8, alignment: .end)
    }
```

<img width="494" alt="image" src="https://user-images.githubusercontent.com/255732/78204517-65d1e580-74a2-11ea-9dc8-3bb5b8afd8fa.png">

**Comment by fermoya** [comment]
HI @ramunasjurgilas ,

Apologies for the late response. I just fixed this and released version 1.4.0-beta.1. Could you please try again and let me know if it solves your problem?

Thanks

**Comment by ramunasjurgilas** [comment]
Thanks for the fix! I did not have time to test it. But I will let you know when I will do it.

**Comment by ramunasjurgilas** [comment]
I tested and it works good. :)
