### ISSUE TITLE
[FEAT]

### ISSUE THREAD

**Issue by iKK001** [fermoya/SwiftUIPager#210]
Fantastic tool, thank you very much !

There is one feature that I would like to have inside SwiftUIPager:

When I use a ZoomableScrollView (see code below), then swiping your pages does no longer work when the content is zoomed.

I created a video - it shows how I swipe several portrait images, ....until the image where I zoom - there is stalls. I cannot go further to the next page when the image is zoomed and I scrolled on it !

My workarround is to zoom back to original size - then swiping works again. But this is not what the user expects since native behaviour is that swiping gestures continue to work even tough you have your image zoomed. It should just "jump" to the next page.

https://user-images.githubusercontent.com/8404556/113918419-b3361080-97e2-11eb-8e26-8be8795522ca.mp4

My Pager modifiers are:

```Swift
            .pagingPriority(.simultaneous)
            .swipeInteractionArea(.allAvailable)
            .sensitivity(.high)
            .delaysTouches(true)
            .bounces(true)
```

Here is how my Zoomable Page looks like:

```Swift\
import SwiftUI

ZoomableScrollView {
    Image(uiImage: UIImage(contentsOfFile: url.path)!)
       .resizable()
       .scaledToFit()
 }
```

And here the ZoomableScrollView code:

```Swift

struct ZoomableScrollView<Content: View>: UIViewRepresentable {
    
    private var content: Content
    
    init(@ViewBuilder content: () -> Content) {
        self.content = content()
    }
    
    func makeUIView(context: Context) -> UIScrollView {
        
        // set up the UIScrollView
        let scrollView = UIScrollView()
        scrollView.delegate = context.coordinator  // for viewForZooming(in:)
        scrollView.maximumZoomScale = 20
        scrollView.minimumZoomScale = 1
        scrollView.bouncesZoom = true
        
        // create a UIHostingController to hold our SwiftUI content
        let hostedView = context.coordinator.hostingController.view!
        hostedView.translatesAutoresizingMaskIntoConstraints = true
        hostedView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        hostedView.frame = scrollView.bounds
        hostedView.backgroundColor = .black
        scrollView.addSubview(hostedView)
        
        return scrollView
    }
    
    func makeCoordinator() -> Coordinator {
        return Coordinator(hostingController: UIHostingController(rootView: self.content))
    }
    
    func updateUIView(_ uiView: UIScrollView, context: Context) {
        // update the hosting controller's SwiftUI content
        context.coordinator.hostingController.rootView = self.content
        assert(context.coordinator.hostingController.view.superview == uiView)
    }
    
    // MARK: - Coordinator
    
    class Coordinator: NSObject, UIScrollViewDelegate {
        var hostingController: UIHostingController<Content>
        
        init(hostingController: UIHostingController<Content>) {
            self.hostingController = hostingController
        }
        
        func viewForZooming(in scrollView: UIScrollView) -> UIView? {
            return hostingController.view
        }
    }
}
```

**Comment by fermoya** [comment]
Hi @iKK001 , have you tried using `delayTouches(false)`? 

You can also try implementing `onDragChanged`. If that callback isn't called it means there's something in your `ZoomScrollView` that's not propagating the touches to `Pager`

**Comment by iKK001** [comment]
The `delayTouches(false)` makes it worse, in a sense that now I can zoom but no longer scroll arround in my ZoomableScrollView.

The Pager swipe shall only ocurr when a border-side reached and continuing swiping (see video below).

The ZoomableScrollView can only zoom & scroll - but it cannot swipe pages when on the edge. Therefore I assume your PagerView should detect when a child-view reaches the edge of some sort.

I am not sure if I am asking too much. I just wonder how we could reproduce the native Photos-App behaviour like seen on this video ?

https://user-images.githubusercontent.com/8404556/113934769-72e08d80-97f6-11eb-943a-e436635f3a09.mp4

**Comment by iKK001** [comment]
P.S. The `onDragChanged` does fire...

**Comment by fermoya** [comment]
Hi @iKK001 , you're not asking too much. I checked and `onDraggingChanged` isn't called if the image is zoomed (just if the image has the normal scale). This means that when the user is zoomed, the touches aren't propagated to `Pager` which means there's something wrong in your `ZoomableScrollView` that prevents this form happening

**Comment by iKK001** [comment]
ok - thank you very much !  I'll have a look at that.

**Comment by fermoya** [comment]
Here, try this implementation:
```swift
struct ZoomableScrollView<Content: View>: View {
  
  private var content: Content
  @State private var scale: CGFloat = 1
  
  init(@ViewBuilder content: () -> Content) {
    self.content = content()
  }
  
  var body: some View {
    ScrollView {
      content
        .scaleEffect(scale)
        .gesture(
          MagnificationGesture()
            .onChanged({ value in
              scale = value.magnitude
            })
        )
    }
  }

}
```
It obviously needs some work. `Pager` should receive the drag only if the view is at the edge, as you mentioned. But that's not something than `Pager` can know, but something you should control

**Comment by iKK001** [comment]
This scoolbook example I know. However there are many things not quite useful with this kind of ZoomableScrollView. Most of all, the zooming always starts at scale = 1. And also, the scrolling-effect is not yet in there. So far, it is only a `ZoomableFromScale1View`  (but not `ZoomableScrollView`).

Here is my implementation of `ZoomableScrollVie` (i.e. it relies on the UIKit ScrollView).

Do you know how I could add this page-swipe behaviour into this kind of implementation ?

```Swift
import SwiftUI

struct ZoomableScrollView<Content: View>: UIViewRepresentable {
    
    @Binding var didZoom: Bool
    
    private var content: Content
    
    init(didZoom: Binding<Bool>, @ViewBuilder content: () -> Content) {
        _didZoom = didZoom
        self.content = content()        
    }
    
    func makeUIView(context: Context) -> UIScrollView {
        
        // set up the UIScrollView
        let scrollView = UIScrollView()
        scrollView.delegate = context.coordinator  // for viewForZooming(in:)
        scrollView.maximumZoomScale = 20
        scrollView.minimumZoomScale = 1
        scrollView.bouncesZoom = true
        
        // create a UIHostingController to hold our SwiftUI content
        let hostedView = context.coordinator.hostingController.view!
        hostedView.translatesAutoresizingMaskIntoConstraints = true
        hostedView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        hostedView.frame = scrollView.bounds
        hostedView.backgroundColor = .black
        scrollView.addSubview(hostedView)
        
        return scrollView
    }
    
    func makeCoordinator() -> Coordinator {
        return Coordinator(hostingController: UIHostingController(rootView: self.content), didZoom: $didZoom)
    }
    
    func updateUIView(_ uiView: UIScrollView, context: Context) {
        // update the hosting controller's SwiftUI content
        context.coordinator.hostingController.rootView = self.content
        assert(context.coordinator.hostingController.view.superview == uiView)
    }
    
    // MARK: - Coordinator
    
    class Coordinator: NSObject, UIScrollViewDelegate {
        
        var hostingController: UIHostingController<Content>
        @Binding var didZoom: Bool
        
        init(hostingController: UIHostingController<Content>, didZoom: Binding<Bool>) {
            self.hostingController = hostingController
            _didZoom = didZoom
        }
        
        func viewForZooming(in scrollView: UIScrollView) -> UIView? {
            return hostingController.view
        }
        
        func scrollViewDidZoom(_ scrollView: UIScrollView) {
            didZoom = (scrollView.zoomScale == scrollView.minimumZoomScale)
        }
    }
}
```

**Comment by fermoya** [comment]
@iKK001 there might be a way to get that info via `UIScrollViewDelegate`
