### ISSUE TITLE
Integration with PagingControl

### ISSUE THREAD

**Issue by iKK001** [fermoya/SwiftUIPager#212]
Maybe I am too new in SwiftUI. I tried to integrate [PagingControl](https://github.com/franklynw/PagingControl) in order to achieve the little dots for your Pager.

However, I completely fail with this integration.

I tried what I described [here](https://github.com/franklynw/PagingControl/issues/1#issue-853544043)

Can you please give me a hint on how to do so. I do not get any responce from the developer of PagingControl. And I am stuck with this since 4 hours.
Thank you very much. Hope this is my last question for you for today ;) I appreciate an example intergration.

**Comment by fermoya** [comment]
Hi @iKK001. In fairness, I’ve never used that framework but I know this user was dealing with something similar to your problem and created that framework.

At the end of the day, your `PageControl` is nothing other than an `HStack` with a `ForEach` inside (resembling `Pager` arguments, you wanna use `data.indexes` as the input and `\.self` as the `id`). This `ForEach` has a `Circle` in its `ViewBuilder` (customize the circle according to your needs, give it a fixed size...). Finally, use the argument in `ForEach` callback and compare it with `page.index`. If it matched, use a `scaleEffect(_:)` to animate the focused circle. Use `animation` to change the animation to the one you want

**Comment by fermoya** [comment]
Closing as `SwiftUIPager` is not responsible for the integration of any `PagingControl`
