### ISSUE TITLE
[FEAT] "tap to top" when tapping top right of status bar for `vertical` pagers

### ISSUE THREAD

**Issue by garrettmaring** [fermoya/SwiftUIPager#215]
**Is your feature request related to a problem? Please describe.**

For vertical pagers, I'd love a modifier that lets me enable "tap to top" as is seen in other vertically scrolling/feed-based apps.

**Describe the solution you'd like**
An opt-in modifier to enable tapping on the top-right of the status bar to animate the vertical pager back to index 0.

**Describe alternatives you've considered**
Just manage it with the index state myself.

**Comment by fermoya** [comment]
Hi @garrettmaring , please see [this answer](https://github.com/fermoya/SwiftUIPager/issues/117#issuecomment-678485009) and let me know if it makes sense

**Comment by garrettmaring** [comment]
Ah, I wish Swift had this! I did some digging and couldn't find anything (as your answer states as well).
