### ISSUE TITLE
How to update based on parent? Eg. Change in orientation.

### ISSUE THREAD

**Issue by Priva28** [fermoya/SwiftUIPager#22]
When the orientation of the device changes or the window is resized in macOS. The page item does not take up all the available space. Is there a way to do that? Thanks!

```
import SwiftUI
import SwiftUIPager

struct MainView: View {
    
    @State var page: Int = 0
    @State var pages = Array(0..<2)
    
    var body: some View {
        Pager(page: self.$page, data: self.pages, id: \.self, content: { page in
            PageView()
        })
            .itemSpacing(10)
            .expandPageToEdges()
    }
}

struct PageView: View {
    var body: some View {
        Rectangle()
            .foregroundColor(.red)
    }
}
```
[Video](https://imgur.com/a/gF9T7EX)

**Comment by fermoya** [comment]
Hi @Priva28 ,

Thanks for your feedback and sorry for the late response. I've seen the issue and I've managed to fix it. Nonetheless. I wanna spend a bit of time here to figure out a better solution as I don't like the result very much.

I'll keep you posted

**Comment by fermoya** [comment]
Hi @Priva28 ,

I've drafted a beta version 1.4.0-beta.2 with this fix. Now the page will be resized when `Pager` frame changes.

Could you confirm this works for you, please?

Thanks

**Comment by Priva28** [comment]
No problem whatsoever. It’s an amazing package that Apple should have made ages ago! 

Yes I can confirm that the fix does work. I have tested on my Mac and my iPad and it successfully resizes depending on window size, orientation change etc.

Thanks.

**Comment by fermoya** [comment]
Thanks for the kind words.
