### ISSUE TITLE
Could not find module 'SwiftUIPager' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator on macbook m1

### ISSUE THREAD

**Issue by cikpis** [fermoya/SwiftUIPager#227]
Hi there!

Using SPM with a MacBook Pro M1 I'm facing this issue:
```
Could not find module 'SwiftUIPager' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator
```

In base of this answer seems that you need to re-release with "build active architecture only" set to "No" for both Debug & Release.
https://github.com/airbnb/lottie-ios/issues/1293#issuecomment-855416295

Could you release a new version with that setting?

Thanks

**Comment by fermoya** [comment]
Hi @cikpis , have you checked the follow-up comment from the same user? Seems like it's a user-side issue:

https://github.com/airbnb/lottie-ios/issues/1293#issuecomment-855423580

**Comment by fermoya** [comment]
Another workaround seems to be here:

https://developer.apple.com/forums/thread/123614

Just by opening Xcode with Rosetta.
