### ISSUE TITLE
[BUG] smooth scroll not trigger onPageChanged

### ISSUE THREAD

**Issue by JackKFouani** [fermoya/SwiftUIPager#229]
**Describe the bug**
after updating for last version , when i smooth scroll between full screen pages horizontally , the onPageChanged callback is not trigger if the array size feed comes from environment published object , but when i scroll fast its working

**To Reproduce**

```
class Env:ObservableObject {
     @Published var stories:[DTO_STORYBITE] = []
.......
```

the pager in contentView

```
        Pager(page: self.page,
                  data: Array(0..<Env.shared.stories.count - 1),
                  id: \.self,
                  content: { i in
```

**Expected behavior**
trigger onPageChanged

**Screenshots / Videos**

**Environment:**
 - OSX: MacOs Big Sur
 - Device iPhone Xs
- SwiftUIPager (2.3.1)

**Additional context**
i was able to fix it by feeding the pager array size from same contentView as @State object

**Comment by fermoya** [comment]
Hi @JackKFouani , what do you mean by:
> i was able to fix it by feeding the pager array size from same contentView as @State object

? Can you show me your `Env.shared` definition please?

What version were you using previously?
