### ISSUE TITLE
Question: taking one of the pages from the pager into full screen mode

### ISSUE THREAD

**Issue by edimoldovan** [fermoya/SwiftUIPager#232]
@fermoya great work with the library, I love it! I used it already multiple times.

Let me know if this question should go somewhere else like SO maybe.
My question is regarding a suggested way of taking one of the views (one page) into full screen, with an animation. Anyone done that with this specific Pager.  What I am trying to do is animate the same view that I have in a the page based on a toggle value.
Challenges I'm running into right now are that all this is in a NavigationView with a TabBar and both stay visible. This is not a SwiftUIPager specific question maybe, looking into how to hide those -- but I was wondering if anyone tried this.

**Comment by fermoya** [comment]
Hi @edimoldovan .
Unfortunately I can't refer any other issue in this repo as no one has ever suggested this behavior. You're right to think this is out of this library scope.

Out of curiosity, how are you handling that transition? Can you share some code or pseudo-code?

**Comment by edimoldovan** [comment]
@fermoya I'll try to explain. Let me know if i should share more.

I have a Pager initialised something like this:
`Pager(...) {
                       SomeView()
                    }
                    .pagingPriority(.simultaneous)
                    .edgesIgnoringSafeArea(.all)`

I also watch for the currently displayed page so that I animate that one only to fullscreen. Then I have a full screen toggle binding that I pass into SomeView() and tggle that in a withAnimation {...}. The reason I pass the binding in is that I prevent the fullscreen swipe like that by disabling in .allowsDragging(...) on the Pager. 
It is actually interesting, because after putting the page in full fullscreen mode, the Pager still works, so could be an interesting use case for specific journeys.

Now that wrote this down, what do you think @fermoya , would be valuable to put part of this logic in PR in some way? Maybe others could use it.

**Comment by fermoya** [comment]
Hi @edimoldovan , I asked about the transition specifically. I don’t think there’s  currently a way to do custom transitions the right way. I wrote an article about it, find it [here](https://link.medium.com/saze0Rby9ib). I believe this hasn’t changed.

That’s what you’re experiencing here. This gives you trouble expanding to the edges and covering the navbar or tabbar. From my point or view, this is unrelated with the purpose of the library which is offering a customizable component to page.

Nonetheless, I encourage you to dig into it. If anything comes up please let me know, I’m interested. Or if you feel you can contribute to the library, feel free to send a PR
