### ISSUE TITLE
[Question] Is this library planned to be maintained going forward?

### ISSUE THREAD

**Issue by ndonald2** [fermoya/SwiftUIPager#239]
Hello, this is more of a question than an issue so please forgive me not using one of the templates.

Firstly this is an awesome library, really great work! So useful and really nice interactions/animations.

I am wondering if the author (@fermoya) is planning to continue actively maintaining this library? As I'm sure you know, for production apps developers need to weigh adding new third party dependencies based on how actively maintained they are and are likely to be in the future. My team is considering adopting this library for our app and it would be helpful to know what, if any, future plans/commitments the author has to maintaining it (either themselves, or handing off ownership to another developer or the community). Just wondering!

Sincere thanks, and once again great work on this project!

**Comment by fermoya** [comment]
Hi @ndonald2 , that’s a valid question. My plan is to keep maintaining but I’ve found it hard to keep making additions lately. This is an open source library and currently I’m the only person actively working on it. I always count on people to contribute.

**Comment by ndonald2** [comment]
Thank you, I appreciate the response! Totally get how hard it is to maintain OSS and nothing but respect for it. I'm less concerned about new features just making sure it doesn't "break" (any major bugs get fixed) and it doesn't become deprecated but of course yes community contributions are key :)

Cheers!
