### ISSUE TITLE
[BUG] loopPages() with small number of items is animating to wrong end of the Pager.

### ISSUE THREAD

**Issue by mikepitre** [fermoya/SwiftUIPager#244]
**Describe the bug**
When using `loopPages()` with a small number of items (eg. 3), if I swipe on the last item, the pager scrolls all the way back to the beginning (or end) instead of just scrolling to the next item. 

**To Reproduce**

In the `InfiniteExampleView`, set `data2` to `Array(0..<3)`
Apply the modifier `.loopPages(true, repeating: 10)` on the looping pager.
Attempt to page through the end of the Pager. Try in both directions.

**Expected behavior**

I expected the pager to scroll forward to the next item (which would be the item at index 0). 
(And I would expect the opposite when going in the other direction as well)

**Screenshots / Videos**

https://user-images.githubusercontent.com/12040919/147604197-d6b92aaf-0532-4f83-9b7f-0b3863a29505.mp4

**Environment:**
- iOS 15.2
- iPhone 13 (Simulator)
- SwiftUIPager version 2.3.2

**Comment by fermoyadrop** [comment]
@mikepitre thank for your feedback and apologies for leaving this unattended for so long. I'll be soon releasing a fix for this

**Comment by fermoya** [comment]
hi @mikepitre , apologies for the late response. This should be fixed [here](https://github.com/fermoya/SwiftUIPager/releases/tag/2.3.3-beta.3):
https://github.com/fermoya/SwiftUIPager/releases/tag/2.3.3-beta.3

**Comment by mikepitre** [comment]
ty @fermoya !
