### ISSUE TITLE
[BUG] loopPages + scale. First and last elements not scaling up

### ISSUE THREAD

**Issue by darecki** [fermoya/SwiftUIPager#259]
**Describe the bug**
When using the infinite pager (`loopPages()`) with scale (`.interactive(scale: xxx)`) the first and last elements are not properly scaled up.

**To Reproduce**
To reproduce this behavior it's enough to add `.interactive(scale: 0.6)` to the `InfiniteExampleView` example provided

**Expected behavior**
I expect to see the next element scaling up when dragging between the first and last elements on the list.

**Screenshots / Videos**

https://user-images.githubusercontent.com/3084606/160618413-fed09eae-2c1f-4bc3-affb-059d4f3f36fd.mp4

See the video and compare the animation when dragging between: 
- Page 0 and Page 1 (works great)
- Page 19 and Page 0 (doesn't scale up) 

**Environment:**
 - OSX: iOS 14, 15
 - Device any
- SwiftUIPager version 2.3.2

**Comment by fermoya** [comment]
It should be fixed in [2.3.3-beta.5](https://github.com/fermoya/SwiftUIPager/releases/tag/2.3.3-beta.5)
