### ISSUE TITLE
[BUG] With vertical pagination, it interferes with horizontal swipe in `TabView` on watchOS

### ISSUE THREAD

**Issue by andriy-appuchino** [fermoya/SwiftUIPager#274]
**Describe the bug**
There is a problem on watchOS. If `Pager` is in `TabView` like in an example, then switching between tabs from left to right very often does not work. Probably `Pager` is blocking gestures horizontally somewhere.

**To Reproduce**
1. Download and unzip [PagerInTabView.zip](https://github.com/fermoya/SwiftUIPager/files/8459964/PagerInTabView.zip)
2. Run project on simulator or watch2. 
3. Try swiping left or right on a screen with vertical pagination (yellow or red background).
4. Horizontal swipe very often does not work.

**Expected behavior**
Stable operation of swipe left and right every time.

**Screenshots / Videos**

https://user-images.githubusercontent.com/49787488/162640669-19e93316-f19a-4a39-9f3b-d0fcc2086ca9.mov

**Environment:**
 - OS: watchOS 8
 - Device: any Apple Watch
- SwiftUIPager version: 2.4.0

**Additional context**
Pay attention that on other screens where `Pager` is not used (green or blue background) horizontal swipe works in 100% of cases.

**Comment by fermoya** [comment]
@andriy-appuchino apologies but I haven't had time to look at this and I don't think I will within the next days.

Some people have mentioned this a while ago, here are some hints that would solve this issue:
- Try using [`pagingPriority(.simultaneous)`](https://github.com/fermoya/SwiftUIPager/blob/b2d2e54fab33163dbb430af3c6875917ed24b4c4/Sources/SwiftUIPager/Pager%2BBuildable.swift#L127). This will allow the `DragGesture` inside `Pager` to propagate the touch event.
- If this still doesn't have the desired effect, I'd suggest embedding the vertical `Pager` inside a horizontal `Pager` and deal with the page indicator yourself. The vertical `Pager` should use the modifier mentioned in the previous bullet

Hope that helps

**Comment by andriy-appuchino** [comment]
1. Just using `pagingPriority(.simultaneous)` doesn't help.
2. I tried to use a horizontal `Pager`, but the problem is no less serious with it. If there are buttons on the page, then they are constantly accidentally pressed when swiping. Normally, if the beginning of the movement of the finger hits the button, then it should not trigger.

@fermoya do you know how to fix case 2?

**Comment by fermoya** [comment]
@andriy-appuchino have you tried using `onTapGesture` or `gesture(TapGesture().onEnded {})` instead of a `Button`? That could do the trick, I believe that if swiping, those gestures should get canceled and the callbacks should never be called. Same can't be said about `Button`, but it's just a guess

**Comment by andriy-appuchino** [comment]
No, I haven’t, I don’t want to give up buttons so as not to lose their visual effects.

I was able to interrupt a button touch in during a swipe using `.disabled(areControlsDisabled)` and
```
.onDraggingBegan({
	 areControlsDisabled = true
})
.onDraggingEnded({
	 areControlsDisabled = false
})
```

Nevertheless, thanks for the help.

P.S. I recommend disabling `digitalCrownRotation` by default for the horizontal `Pager`, because it is very unusable.

**Comment by fermoya** [comment]
Closing this as it's a similar problem as #153
