### ISSUE TITLE
[FEAT] Support Right-to-Left scroll in Hebrew locale

### ISSUE THREAD

**Issue by sdavidliu** [fermoya/SwiftUIPager#280]
**Is your feature request related to a problem? Please describe.**
After adding Hebrew to Supported Localization, I noticed that the scrolling will scroll in the opposite direction of where I am swiping. So if I try to swipe to the card on the left, it actually scrolls to the right. If I swipe to the card on the right, it scrolls to the left.
It's nice that it correctly places the items with the first item at the very right. 2nd item to its left. etc. However, the dragging animation is flipped around and may be counter-intuitive for users.

**Describe the solution you'd like**
Support scrolling in the correct direction for right-to-left locales.

**Describe alternatives you've considered**
N/A

**Additional context**
<img width="1359" alt="Screen Shot 2022-05-18 at 11 42 21 AM" src="https://user-images.githubusercontent.com/16772059/169121760-e53cf2c7-fd31-4654-9980-5b197b282c5d.png">

**Comment by fermoya** [comment]
should be done in `2.5.0-beta.1`, do you mind giving me some feedback @sdavidliu please?

**Comment by sdavidliu** [comment]
Hi @fermoya , thanks for the quick turnaround! It is mainly working as expected; however, on some of my swipes (especially when I reach the end) it still scrolls to the opposite direction. Not sure if it's happening when I scroll fast enough, but it seems a bit random. I attached a video in Arabic locale:

[2.5.0-beta.1-arabic.mov.zip](https://github.com/fermoya/SwiftUIPager/files/8741944/2.5.0-beta.1-arabic.mov.zip)
