### ISSUE TITLE
 SwiftUIPager breaks on ScrollView 

### ISSUE THREAD

**Issue by Mohsenqaysi** [fermoya/SwiftUIPager#3]
When added into a ScrollView for some reasons it will not scroll.

**Comment by fermoya** [comment]
Thanks for issue.

There were some issues related to the Gestures. I've created a new version [1.1.1](https://github.com/fermoya/SwiftUIPager/releases/tag/1.1.1) that should fix your problem.

Any other issues, don't hesitate to let me know

**Comment by ggagosh** [comment]
@fermoya Hallo,

First of all thanks for this package <3. 

I have a problem with ScrollView and SwiftUIPager. When I try to add SwiftUIPager inside the pager it's broken. For example, my `pageView` looks like this:

```swift
func pageView(_ page: Int) -> some View {
        ZStack {
            ScrollView {
                VStack(spacing: 20) {
                    ForEach(0..<10) {
                        Text("Item \($0)")
                            .foregroundColor(.white)
                            .font(.largeTitle)
                            .frame(width: 200, height: 200)
                            .background(Color.red)
                    }
                }
            }
        }
    }
```

I have latest version of this library: 1.2.0

**Comment by fermoya** [comment]
Hi @ggagosh,

Thanks so much, I'm glad you find it useful. 

I find it bizarre what you're trying to achieve here. So, are you trying to add a ScrollView as the Pager page?  From what I can see, this code would add 10 items to a vertical scroll and this would be repeated as many times as pages has the Pager.

Are you trying to do something like this?
```swift
struct ContentView: View {

    @State var isPresented: Bool = false
    @State var pageIndex: Int = 0
    var data: [Int] = Array((0...10))
    
    var body: some View {
        GeometryReader { proxy in
            Pager(page: self.$pageIndex,
                  data: self.data,
                  id: \.self,
                  content: { index in
                    self.pageView(index)
            })
                .itemSpacing(20)
                .padding(20)
                .alignment(.start)
                .vertical()
                .border(Color.black)
        }
    }

}

extension ContentView {
    func pageView(_ page: Int) -> some View {
        ZStack {
            Rectangle()
                .fill(Color.red)
            Text("Item \(page)")
                .foregroundColor(.white)
                .font(.largeTitle)
        }
    }
}
```

**Comment by ggagosh** [comment]
@fermoya So I want to add a scroll view into the page. For example:

I have some articles (scrollable ones: image/text/etc) and I need to add this content in your pager page.

I just need a solution to add ScrollView with different content on every page.

**Comment by fermoya** [comment]
@ggagosh I got what you mean, apologies.

I just released a beta version, 1.2.3-beta.1

I'm letting the page take up the whole space available by default if `itemAspectRatio` is not specified. Here's a sample page:
```swift
    func pageView(_ page: Int) -> some View {
        ZStack {
            Rectangle()
                .fill(Color.red)
            ScrollView {
                ForEach(Array(0...10), id: \.self) { index in
                    Text("Item \(index) in \(page)")
                        .foregroundColor(.white)
                        .font(.largeTitle)
                        .frame(width: 200, height: 200)
                        .background(Color.yellow)
                }
            }.border(Color.black)
        }
    }
```
And the result:

![simulator](https://user-images.githubusercontent.com/11335612/73468099-2f7dca00-437c-11ea-9b01-6ad2542e1264.gif)

Does this solve your issue?

**Comment by ggagosh** [comment]
@fermoya Thanks very much. 

It's working like a charm <3

**Comment by fermoya** [comment]
@ggagosh, I'm glad to hear that. I'll release 1.2.3 within the next days
