### ISSUE TITLE
The pager don't have the expected height

### ISSUE THREAD

**Issue by xiaocairush** [fermoya/SwiftUIPager#30]
issue:
The pager don't have the expected height.<br/>
seems like the view is clipped at [this line](https://github.com/fermoya/SwiftUIPager/blob/master/Sources/SwiftUIPager/Helpers/SizeViewModifier.swift#L32).

complete code to reproduce the issue:

```
import SwiftUI
import SwiftUIPager

struct IssueView: View {
    @State var page: Int = 0
    
    @State var data = Array(0..<10)
    
    var body: some View {
        VStack(alignment: .leading){
            
            HStack {
                VStack(alignment: .leading) {
                    HStack {
                        Text("4").font(.title).foregroundColor(Color("defaultColor"))
                        Text("月")
                    }.padding(.bottom, 10)
                    Text("月份").padding(.leading, 10)
                        .padding(.trailing, 10)
                        .foregroundColor(Color.white)
                        .background(Color("defaultColor"))
                }.padding(.leading, 20).padding(.trailing, 10).fixedSize(horizontal: true, vertical: false)
                Divider()
                
                
                Pager(page: self.$page,
                      data: self.data,
                      id: \.self) {
                        self.pageView($0)
                }.fixedSize(horizontal: false, vertical: false)
                //                self.pageView(0)
            }.fixedSize(horizontal: false, vertical: true)
            Divider()
            List {
                Text("test")
            }.frame(maxHeight: .infinity)
        }.padding()
    }
    
    func pageView(_ page: Int) -> some View {
        HStack{
            IssueItemView().frame(maxWidth: .infinity)
            IssueItemView().frame(maxWidth: .infinity)
            IssueItemView().frame(maxWidth: .infinity)
            IssueItemView().frame(maxWidth: .infinity)
            IssueItemView().frame(maxWidth: .infinity)
            IssueItemView().frame(maxWidth: .infinity)
            IssueItemView().frame(maxWidth: .infinity)
        }.background(Color.yellow)
    }
}

struct IssueItemView: View {
    var body: some View {
        VStack(spacing: 10) {
            Text("日")
            Text("5")
            Text("行").background(Color.gray).foregroundColor(Color.white)
        }
    }
}

struct IssueView_Previews: PreviewProvider {
    static var previews: some View {
        IssueView()
    }
}
```

**Comment by fermoya** [comment]
Hi @xiaocairush ,

`clipped` just makes sure that a `View` doesn't display anything beyond its bounds. You can check `Pager` doesn't have the right frame if you debug the view hierarchy after running your code:

<img width="648" alt="Screenshot 2020-04-10 at 18 41 02" src="https://user-images.githubusercontent.com/11335612/79010920-db048100-7b5a-11ea-8958-bb467774f6ff.png">

`Pager` doesn't have an intrinsic size but calculates its size based on the available space (it uses a `GeometryReader` for that). That means it has no fixed size like a `Toggle` or a `Text`. `GeometryReader` will return the available size in the container `Pager` is in and this size is determined by your inner-most `VStack`. Its content makes it have a height of 64 pixels in an iPhone 11 Pro Max which isn't enough for to display a page.

This is the piece of code that needs to change:
```
VStack(alignment: .leading) {
        HStack {
               Text("4").font(.title).foregroundColor(Color.red)
                Text("月")
         }.padding(.bottom, 10)
               Text("月份").padding(.leading, 10)
                      .padding(.trailing, 10)
                      .foregroundColor(Color.white)
                      .background(Color.red)
}.padding(.leading, 20).padding(.trailing, 10).fixedSize(horizontal: true, vertical: false)                
```
You have 2 options here. Either you give `Pager` a fixed height:
```
Pager(...).frame(height: 80)
```
or you make the vertical stack view above expand in the Y-Axis by modifying some of the multiple paddings there are. For example, this could do the trick:
```
HStack {
      Text("4").font(.title).foregroundColor(Color.red)
      Text("月")
}.padding(.vertical, 15)
```
<img width="438" alt="Screenshot 2020-04-10 at 19 11 56" src="https://user-images.githubusercontent.com/11335612/79012950-81528580-7b5f-11ea-87e8-6046d7a9a493.png">

**Comment by xiaocairush** [comment]
Thanks @fermoya , I'm a newer to swiftui,  but I noticed that if just remove Pager , we can get the expected height:

```

import SwiftUI
import SwiftUIPager

struct IssueView: View {
    @State var page: Int = 0
    
    @State var data = Array(0..<10)
    
    var body: some View {
        VStack(alignment: .leading){
            
            HStack {
                VStack(alignment: .leading) {
                    HStack {
                        Text("4").font(.title).foregroundColor(Color("defaultColor"))
                        Text("月")
                    }.padding(.bottom, 10)
                    Text("月份").padding(.leading, 10)
                        .padding(.trailing, 10)
                        .foregroundColor(Color.white)
                        .background(Color("defaultColor"))
                }.padding(.leading, 20).padding(.trailing, 10).fixedSize(horizontal: true, vertical: false)
                Divider()
                
                
                pageView(0)
                //                self.pageView(0)
            }.fixedSize(horizontal: false, vertical: true)
            Divider()
            List {
                Text("test")
            }.frame(maxHeight: .infinity)
        }.padding()
    }
    
    func pageView(_ page: Int) -> some View {
        HStack{
            IssueItemView().frame(maxWidth: .infinity)
            IssueItemView().frame(maxWidth: .infinity)
            IssueItemView().frame(maxWidth: .infinity)
            IssueItemView().frame(maxWidth: .infinity)
            IssueItemView().frame(maxWidth: .infinity)
            IssueItemView().frame(maxWidth: .infinity)
            IssueItemView().frame(maxWidth: .infinity)
        }.background(Color.yellow)
    }
}

struct IssueItemView: View {
    var body: some View {
        VStack(spacing: 10) {
            Text("日")
            Text("5")
            Text("行").background(Color.gray).foregroundColor(Color.white)
        }
    }
}

struct IssueView_Previews: PreviewProvider {
    static var previews: some View {
        IssueView()
    }
}
```

**Comment by fermoya** [comment]
Hi @xiaocairush ,

That’s right. In case of single page, which is just a combination of `Text` views, you’ll have an intrinsic content size. But once you wrap it into `Pager` you’ll need to specify a size as it’s a scroll. There’s no way in `SwiftUI` to get the intrinsic content size, at least for now. Otherwise, I could choose between the available space given by `GeometryReader` and the page's content size.

**Comment by xiaocairush** [comment]
@fermoya emm.... Sounds like we cannot solve this issue elegantly in swiftui for now. All what we can do is to declare the height as intrinsic. I think it's a workaround instead of a solution for this issue. I will solve the issue by the workaround and still hope any possiable elegant solution.

**Comment by fermoya** [comment]
Hi @xiaocairush ,

If you have experience working with `UIKit` you'll see that `UIScrollView` needs an explicit size. You give it to it by applying constraints, but you still have to give it some value. It's not that it isn't elegant, it's the way it is. I'll leave you here a nice tutorial to better understand how it works in SwiftUI.

https://sarunw.com/posts/intrinsic-content-size-in-swiftui/

Cheers
