### ISSUE TITLE
[FEAT] Page Indicator dots (`PageTabViewStyle.IndexDisplayMode`) at the bottom according page count

### ISSUE THREAD

**Issue by rb090** [fermoya/SwiftUIPager#313]
**Is your feature request related to a problem? Please describe.**

I started using SwiftUIPager. I like it a lot. I want to use it, because I want to show a pager where the end of the previous element and the begging of the next element in the pager is visible:

<img width="170" alt="Bildschirm­foto 2023-03-30 um 10 54 16" src="https://user-images.githubusercontent.com/59200033/228783727-3fd64c4a-01cd-4773-8453-134cab13a27d.png">

There is only one thing I am missing atm. This is a page indicator about the current page index like SwiftUI has for the `TabView` element. When I use `TabView` I am setting `tabViewStyle` to `page` and there I can specify the `PageTabViewStyle.IndexDisplayMode`:

```
TabView {
    ....
}
.tabViewStyle(.page(indexDisplayMode: .always))
```

This results in:

<img width="170" alt="Bildschirm­foto 2023-03-30 um 10 07 54" src="https://user-images.githubusercontent.com/59200033/228773647-3f8c2b97-9be2-47aa-8b69-de9e5128173a.png">

**Describe the solution you'd like**

It would be nice to please have a `ViewModifier` for the `Pager` element to enable displaying those index indicator dots at the bottom. 

But maybe there is already sth like this provided by this library and I did not find it yet? 😬 

**Describe alternatives you've considered**

I considered to implement an own Indicator dots element similar to this:

```
HStack(spacing: 10){
    ForEach((0...items.count-1), id: \.self) { index in
            Circle()
                .fill(Color.black.opacity(currentPage.index == index ? 1 : 0.1))
        .frame(width: 8, height: 8)
        .animation(.spring(), value: currentPage.index == index)
    }
}
.frame(width: Const.Screen.width - 40)
.padding(.bottom, 20)
```

But with this I do not achieve this nice effect of dots getting "fade out" on many elements, which fe. standard on SwiftUI when using `indexDisplayMode`:

<img width="170" alt="Bildschirm­foto 2023-03-30 um 11 02 06" src="https://user-images.githubusercontent.com/59200033/228787305-0a0cc741-e953-4f01-bbec-9c7f468007a7.png">

Plus on many elements I end up in weird behaviors, like the `ForEach` overgrow the `HStack` container:

<img width="170" alt="Bildschirm­foto 2023-03-30 um 10 50 30" src="https://user-images.githubusercontent.com/59200033/228782698-3c654640-34b1-4222-9736-541d90784428.png">

When I add `.clipping()` after the `.frame(...)` on the `HStack` the `ForEach` is in the bounds of `HStack`, but the 1st element of the `ForEach` is not visible and so on. So I run in one problem after the other. 

And with this I have not this "fading and shrinking" out of the page indicator view like with `TabView`

**Additional context**

/

**Comment by fermoya** [comment]
I think a `PageControl` is out of the scope of the library. I leave this to the user to implement if desired
