### ISSUE TITLE
Pager not shown when using inside ScrollView

### ISSUE THREAD

**Issue by MujtabaMK** [fermoya/SwiftUIPager#317]
Pager not visible when using ScrollView

**Environment:**
 - OSX: iOS 15.1
 - Device: iPhone 11

**Comment by MujtabaMK** [comment]
@fermoya Please check this issue

**Comment by JeremPlln** [comment]
Take a look at the examples, there's one example with a ScrollView.

**Comment by fermoya** [comment]
@MujtabaMK please check out the examples or post some code to check.
