### ISSUE TITLE
View background

### ISSUE THREAD

**Issue by AttemptD** [fermoya/SwiftUIPager#32]
In my app, I set the background of white ,but the Page allways hava a little gray color between tow pages,
how can I to cancel that

**Comment by fermoya** [comment]
Hi @AttemptD ,

Can you share an image or some code, please? So if you go to [SimpleExample](https://github.com/fermoya/SwiftUIPager/blob/master/Example/SwiftUIPagerExample/Examples/SimpleExampleView.swift) and remove lines 28 and 40 (background and shadow) you'll get this:

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-20 at 18 02 11](https://user-images.githubusercontent.com/11335612/79778836-486d9a00-8331-11ea-905a-a7df6f431ccc.png)

As you can see, there's no greyish tone there.

**Comment by AttemptD** [comment]
thank you very much

**Comment by AttemptD** [comment]
@fermoya thank very much

**Comment by fermoya** [comment]
I'll close this then
