### ISSUE TITLE
Infinite scrolling an array

### ISSUE THREAD

**Issue by Alexander-techIOS** [fermoya/SwiftUIPager#34]
Hi, is it possible to loop back over the array. I tried adjusting the $pageIndex in the onPageChanged modifier, if one reaches the end of the list loop back to the beginning or if scrolls towards the beginning loops to the back. But changing the $pageIndex creates a scroll to animation to the index which isn't seamless. Just wondering if you maybe know what could be done?

**Comment by fermoya** [comment]
Hi @Alexander-techIOS,

I think I know what animation you mean. Definitely, this is something worth having so I’ll backlog it and work on that over the next days. I’ll keep you posted

**Comment by Alexander-techIOS** [comment]
Great, awesome library by the way!

**Comment by fermoya** [comment]
Hi @Alexander-techIOS, I just released version 1.5.0-beta.1. Give it a try, I'll release 1.5.0 within the next days if everything looks fine. The new modifier is called `loopPages`

**Comment by Alexander-techIOS** [comment]
Awesome! I will give it a try

**Comment by Alexander-techIOS** [comment]
It works great!

**Comment by fermoya** [comment]
version 1.5.0 released. Use `loopPages` to make an infinite scroll and ensure the number of items is high enough to create a nice UX

**Comment by Alexander-techIOS** [comment]
@fermoya There's an issue with version 1.5.0, how many items are needed? In commit [6e714e106519a5398faceff8e536903178f5643b](https://github.com/fermoya/SwiftUIPager/pull/38/commits/6e714e106519a5398faceff8e536903178f5643b) with 5 items in the array the looping is seamless and works beautifully. But since moving to the official v1.5.0 with a 5 item array every time I swipe to the left the next item "moves" across the screen from left to right and settles into position on the far right.

**Comment by fermoya** [comment]
Hi @Alexander-techIOS ,

There’s a compromise there. The number of items in the `data` array must be greater or equal to the number of items `Pager` keeps in memory. Probably, this latter figure is 6 or more, could you check? 

In the beta version, there was an issue where if the number of items is too low, some cards are hidden. `dataDisplayed` is resorted and that produces the issue you mention. I documented this on the method in version 1.5.0

**Comment by fermoya** [comment]
@Alexander-techIOS I'm gonna give it a thought and see what I can do. Maybe I can adjust the ratio to let `Pager` loop fine with fewer elements... I’ll keep you posted

**Comment by Alexander-techIOS** [comment]
Been a little busy this morning, I'll investigate it a bit. If I just build with 1.5.0-beta it works perfectly with my 5 item array, in the meantime I have set it back to the beta release.

**Comment by fermoya** [comment]
@Alexander-techIOS , version 1.5.1 live
