### ISSUE TITLE
Disable swipe conditionally

### ISSUE THREAD

**Issue by carlosrc** [fermoya/SwiftUIPager#35]
I would like to disable left swipe or right swipe according to a condition. 
This way, you can't move forward until a condition is satisfied.
Is that possible?
Thanks.

**Comment by fermoya** [comment]
Hi @carlosrc ,

Have you tried using `allowsHitting`?

**Comment by carlosrc** [comment]
I don't find that configuration... I try `Pager(...).allowsHitting(...)`, but looks like Pager doesn't have this property.

**Comment by fermoya** [comment]
Hi @carlosrc ,

Sorry, I meant `allowsHitTesting`:
<img width="344" alt="Screenshot 2020-05-22 at 11 22 38" src="https://user-images.githubusercontent.com/11335612/82658308-aafed200-9c1e-11ea-90fb-9eea070e572e.png">

**Comment by carlosrc** [comment]
@fermoya it works, but is there a way to disable only left or right swipe? 

This would be useful, for example, in an app where you have to fill a form before going to the next screen, but you can always go back.

**Comment by fermoya** [comment]
Hi @carlosrc ,

I get you, you want to disable the swiping but not the interaction with the page. I'll add a modifier for this, I'll keep you posted

**Comment by carlosrc** [comment]
Thanks!

**Comment by fermoya** [comment]
Hi @carlosrc , I just released version 1.5.0-beta.1. Give it a try, I'll release 1.5.0 within the next days if everything looks fine

**Comment by fermoya** [comment]
Released version 1.5.0. Use `disableDragging` or `allowsDragging(shouldDrag)`

**Comment by carlosrc** [comment]
Perfect! Great work @fermoya , and thanks for your quick response :)
