### ISSUE TITLE
Compatibility with iOS < 13 projects

### ISSUE THREAD

**Issue by teameh** [fermoya/SwiftUIPager#43]
Thanks for this component, it looks awesome! I wanted to try it out in my iOS 10+ project but unfortunatly that's not possible due to the iOS 13+ target. 

I understand that SwiftUI needs iOS 13+, but I've got a legacy project where I use SwiftUI for some new features that are just disabled for iOS <= 12 users. 

Would it be possible to lower the target and add `@available(iOS 13, *)` (and macOS / watchOS) markers to the code so it can be used in lower target projects as well?

**Comment by fermoya** [comment]
Hi @teameh ,

You are using _Cocoapods_, aren't you? I'm not sure if there's a way to use pods whose _deployment target_ is greater than your project's deployment target. You'd have to create a different target for that.

It doesn't make sense for me to support a lesser iOS version and then do that hack that you mention. I understand your frustration and I'll see if there's something that could please us both.

Nevertheless, have you tried using _SPM_? You can add _SwiftUIPager_ as dependency in SPM and then use `@available(iOS 13, *)` in the files you want to use it.

Hope this solves your issue

**Comment by teameh** [comment]
Hey @fermoya, 

Thanks for the quick reply! 

I used SPM for SwiftUI packages. 

Adding the module works fine but importing it in the code gives a compiler error about the my project having a lower target than SwiftUIPager's target.

**Comment by teameh** [comment]
Just make a quick branch to check if it would work to lower the target and that works indeed fine, see https://github.com/teameh/SwiftUIPager/commit/3a65d7b97b5d405a8118fc7aadc028dce482316d. 

But I understand why you wouldn't want to merge that. This can't be the first project to struggle with this. It's a bit weird that this code compiles fine against 10.0 but you can't use it at runtime. Maybe this is something that should be addressed at SPM.

**Comment by fermoya** [comment]
@teameh , let me make test this over the next days, I'll keep you posted. Thanks for the feedback

**Comment by teameh** [comment]
Cool. I've added a PR of my branch.

**Comment by teameh** [comment]
Also added a question to SO, maybe somebody ran into this before https://stackoverflow.com/questions/62073570/import-community-swiftui-package-with-13-0-target-in-ios-10-project

**Comment by fermoya** [comment]
I've taken a look at other SwiftUI libraries out there and none of them do what you require. You happen to be able to import SwiftUI because Apple needs retrocompatibility, but this framework doesn't.

Please, don't take the wrong way, I understand your frustration. But understand me, I can't lower the support version just for a specific case. The library is build to work with iOS 13.

What you need to do is this. 
* In Xcode, create a new framework and call it _MyApp-iOS13_. 
* Set development target iOS 10.
* Use SPM to download SwiftUIPager or create a new target in the Podfile and specify `platform :iOS, 13`:
```
target 'MyMainTarget'
    platform :iOS, 10
    use_frameworks!

    # my pods
end

target 'MySwiftUITarget'
    platform :iOS, 13
    use_frameworks!

    pod 'SwiftUIPager'
end
```
* Import SwiftUIPager
* Create your custom views and add `@available(iOS 13, *)`. Don't forget to declare them public
* From your main target, use `if #available(iOS 13, *)` to navigate to the SwiftUI views in your newly created target.

**Comment by teameh** [comment]
Yeah I agree, this is not something your library should be fixing. Thanks for the workaround!

And yeah, I agree, ideally we would drop everything but iOS 13, but some apps just need to support old iOS versions for some (corporate) reason..

**Comment by teameh** [comment]
@fermoya just for future readers, I can't get your workaround working. You say that you set the target of the new `MySwiftUITarget` to 10.0 but trying to compile that gives me:  

```
Compiling for iOS 10.0, but module 'SwiftUIPager' has a minimum deployment target of iOS 13.0
```

Setting the target of the that `MySwiftUITarget` proxy framework to 13.0 makes that target compile fine, but compiling the main app gives the same error: 

```
Compiling for iOS 10.0, but module 'MySwiftUITarget' has a minimum deployment target of iOS 13.0
```

I'm going to try this approach now https://stackoverflow.com/a/62079401/672989

**Comment by fermoya** [comment]
@teameh can you try changing `-framework` to `-weak_framework` as specified [here](https://github.com/CocoaPods/CocoaPods/issues/6494)?

**Comment by fermoya** [comment]
@teameh I just did some work around this. I've added support to XCFrameworks so if you follow the instructions in the [README](https://github.com/fermoya/SwiftUIPager/blob/master/README.md) to manually embed the `SwiftUIPager` you should be able to use it. It's easier that all this workaround, and more maintainable till your employer decides to drop iOS 10, 11 and 12.

You can download the binary [here](https://github.com/fermoya/SwiftUIPager/releases/download/1.6.0-beta.2/SwiftUIPager.xcframework.zip).

**Comment by teameh** [comment]
Wow, good work. I was just fiddling with that `-weak_framework` flag when I read your comment. 

Thanks for your effort working on this! This works great without having to do anything else 😊. 

It's a pity it's not under control of a package manager, but I guess one can't have it both ways 😏. 

How did you build this custom binary? Can I build it locally as well?

**Comment by teameh** [comment]
Oh wait, I think I got it https://github.com/fermoya/SwiftUIPager/pull/50/files#diff-012ac64a56ba35be679c11af459ffc10R285. Cool! What did you need to do to make it suitable for iOS 10.0?

**Comment by fermoya** [comment]
@teameh its that commit yeah. I just created an aggregate target and added a script to the build phases. So you just have to open [SwiftPager.xcodeproj](https://github.com/fermoya/SwiftUIPager/tree/master/SwiftUIPager.xcodeproj), build and it will generate the _xcframework_.

I was trying to have it distributed manually and use `weak_framework` but as it is pre-compiled as a binary, Xcode won’t compile it and will link it with no issue. When archiving, Xcode should automatically keep the slices you need (a.k.a arm64, x86_64...).

So xcframeworks are currently supported in Cocoapods but in that case I can’t distribute the source code so I’d rather keep it as it is. Tomorrow I’ll spend some more time on this, but I think the best way is to leave as it is now.

Did it work then? Could `import` the module with no further issue?

**Comment by teameh** [comment]
Yeah I would also indeed favour the source code over the binary. 

Cool. Yes that works with no further issue! 👍

**Comment by teameh** [comment]
> Tomorrow I’ll spend some more time on this, but I think the best way is to leave as it is now.

Maybe I could import the sources with SPM or Cocoapods and add your build script locally in one of the build phases?

**Comment by fermoya** [comment]
So with SPM I think there's no target anywhere for you to do so. You could do it with Cocoapods but it won't work unless you have a target in the _Podfile_ declared with `platform :ios, 13.0`.

All this is because you want to see the Source Code and debug it right?

**Comment by teameh** [comment]
> All this is because you want to be able to see the Source Code and debug it right?

And to [contribute](https://github.com/fermoya/SwiftUIPager/pull/54) back 😄 and test the changes that I've made right away in my production app. 

> Because Cocoapods and SPM just distribute the code.

Ah yeah, of course. 

> So if you want to generate you'd need to download the whole repository or at least the Source Code and SwiftUIPager.xcodeproj.

That works fine, I've cloned the repo, can work on stuff, test it in the example app and try it out in my main app by building the .framework. All good now, thanks for the effort!

**Comment by teameh** [comment]
Crap, I should have tested this on my device. Running on a real device gives me the following:

```
  /private/var/containers/Bundle/Application/E0878F7C-365E-4212-8AC9-CEABE7E80F32/MyApp.app/Frameworks/MySwiftUIProxy.framework/Frameworks/SwiftUIPager.framework/SwiftUIPager: code signature in (/private/var/containers/Bundle/Application/E0878F7C-365E-4212-8AC9-CEABE7E80F32/MyApp.app/Frameworks/MySwiftUIProxy.framework/Frameworks/SwiftUIPager.framework/SwiftUIPager) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
```

This is my structure: 

```
- MyApp
    embeds: 
    - MySwiftUIProxy.framework
        embeds:
        - SwiftUIPager.framework
```

Both frameworks are set to Embed & Sign: 

![image](https://user-images.githubusercontent.com/1330668/83869052-36eb2080-a72c-11ea-8a50-e71097aa2ebf.png)

I needed `MySwiftUIProxy.framework` as an intermediate to get the SwiftUI previews working. They don't work if I add the SwiftUI code to the main app due to https://github.com/CocoaPods/CocoaPods/issues/9275. Also building the main app target takes some time, so it convenient to have all the SwiftUI code in a separate framework.

**Comment by fermoya** [comment]
@teameh , yeah I didn't try it in a device either hehe. Can you try changing the _Embed_ options and run? I remember _Emebed & Sign_ isn't the option that Xcode used by default for this _xcframework_, altho it used _Embed & Sign_ for other libraries like Stripe

**Comment by fermoya** [comment]
@teameh , it works for me when I run it on my Mac. I only find some issue when running on devices/simulators with iOS lesser than 13. For some reason, setting SwiftUIPager as optional doesn’t seem to work, but I’ve come up with a workaround for that. In any cases, I don’t get the error you get.

Are you generating the xcframework yourself?

**Comment by teameh** [comment]
I’ll try the other option. 

I tried both generating it myself and using you precompiled framework, both seem to fail.

**Comment by fermoya** [comment]
I've added a branch _legacy-projects_ that decreases the deployment target. I'll be rebasing that branch with every release to support legacy projects. See [Legacy Support](https://github.com/fermoya/SwiftUIPager/blob/master/Documentation/Legacy.md)

**Comment by teameh** [comment]
Thanks. That does sound like a lot of work and also error prone though..

**Comment by fermoya** [comment]
A GitHub Action has been set to rebase _legacy-projects_ branch and keep it up to date with _develop_
