### ISSUE TITLE
Problem with navigationlink

### ISSUE THREAD

**Issue by Novajox** [fermoya/SwiftUIPager#48]
Hello here,
Thanks for the libs, it looks very nice for now :) 
So I'm an Android developper for several years who just started in order to publish my application on the two stores, so I may have done things wrong xD 
I started SwiftUI and it looks very promising.

I have a pager inside a navigationview which contains navigationlinks such as 

```
   Pager(page: $page,
                        data: self.zoneDetailVM.blocs,
                        id: \.self,
                        content: { item in
                            // create a page based on the data passed
                            NavigationLink(destination: BlocDetailUI(bloc: item)) {
                                pageView(item)//(bloc: item, loading: false)
                            }
                        }).itemSpacing(10)
                        .padding(25)
                        .background(Color.gray.opacity(0.2))
                        .frame(height: 200)
```

Everything works perfect execpt navigation.

If I remove navigation link I can scroll without any problems. But if I add it, navigation link has the priority.
I'd say it take the priority of the touch.

Any help would be appreciated . 
I put the two videos to demonstrate .

Cheers 

[videos.zip](https://github.com/fermoya/SwiftUIPager/files/4716346/videos.zip)

**Comment by fermoya** [comment]
@Novajox , unfortunately gestures aren't well designed in SwiftUI at the moment. I could make a quick change to help you but you're gonna end up with something like this: [SwiftUI: NavigationLink and ScrollView drag gesture colliding](https://stackoverflow.com/questions/58440469/swiftui-navigationlink-and-scrollview-drag-gesture-colliding). So, for now, I don't think I'll be changing `gesture` to `simultaneousGesture`. 

The only workaround I can suggest is use `.swipeableArea(.allAvailable)` and use `NavigationLink` on just a part of the page. For instance, the text with some padding as if a button.

Sorry I can't help you more

**Comment by Novajox** [comment]
Hey thanks a lot for the rapid answer :)
I tried something with
 Pager(page: $page,
                        data: self.zoneDetailVM.blocs,
                        id: \.self,
                        content: { item in
                            // create a page based on the data passed
                            NavigationLink(destination: BlocDetailUI(bloc: item)) {
                                pageView(item)//(bloc: item, loading: false)
                            }.highPriorityGesture(DragGesture().onEnded({
                                self.handleSwipe(translation: $0.translation.width)
                            }))
                        })...


    let minDragTranslationForSwipe: CGFloat = 50

    private func handleSwipe(translation: CGFloat) {
        if translation > minDragTranslationForSwipe && page > 0 {
            page -= 1
        } else if translation < -minDragTranslationForSwipe && page < self.zoneDetailVM.blocs.count - 1 {
            page += 1
        }
    }

but it didn't work very well.

I used your trick and it works nice :) 

Thanks a lot

**Comment by fermoya** [comment]
@Novajox , I'm glad it worked. I'm close this as I believe it's a SwiftUI issue. But no worries, I have it in mind. It's one of the first things I want to review as soon as WWDC 2020 takes place.

**Comment by fermoya** [comment]
I've created a new modifier [`pagingPriority`](https://github.com/fermoya/SwiftUIPager/blob/a0cab6693e2fe464f3c5871b877f5efe6313fd71/Sources/SwiftUIPager/Pager%2BBuildable.swift#L45) to choose the best way to embed [`swipeGesture`](https://github.com/fermoya/SwiftUIPager/blob/a0cab6693e2fe464f3c5871b877f5efe6313fd71/Sources/SwiftUIPager/Pager.swift#L211). If you use `pagingPriority(.simultaneous)`, it'll help with pagination when the page contains a `NavigationLink`.

See [_v1.7.0_](https://github.com/fermoya/SwiftUIPager/releases/tag/1.7.0) for more info.
