### ISSUE TITLE
Crash--numberOfPages: Division by zero in remainder operation

### ISSUE THREAD

**Issue by VonZen** [fermoya/SwiftUIPager#63]
init Pager with empty datas, and add modifier: `loopPages()` will trigger crash。

location at: Pager+Helper.swift-----line 142: 
``` swift
return ((page - maximumNumberOfPages / 2) + numberOfPages) % numberOfPages
```

**Comment by fermoya** [comment]
Hi @VonZen ,

Thanks for raising this. I'll release a quick fix in a few days, I'll keep you posted.

Thanks

**Comment by fermoya** [comment]
Hi @VonZen , see [v1.6.2](https://github.com/fermoya/SwiftUIPager/releases/tag/1.6.2) for the fix. Thanks for your feedback.
