### ISSUE TITLE
Scroll animation to sections

### ISSUE THREAD

**Issue by cellininicholas** [fermoya/SwiftUIPager#67]
Hey, amazing paging component, I love it!

I'm still quite a SwiftUI newbie, so I have a question about animation...
```
@State var page: Int = 0
```
I want to be able to set my page index to the start of a different section of items.
For example, page is set to 0, the user pressed a button to go to the 2nd section of pages, so page will get set to 3 (if there are 3 pages per section).
At the moment, when I set page to 3, the view will update immediately to that state.

What might be the best way to support scrolling/animating the pager to the correct page?

Thanks!

**Comment by fermoya** [comment]
Hi @cellininicholas, I understand you want to do something like I do in [`ColorsExampleView`](https://github.com/fermoya/SwiftUIPager/blob/master/Example/SwiftUIPagerExample/Examples/ColorsExampleView.swift)? You need to use `withAnimation`:
```swift
Button(action: {
    withAnimation {
        self.pageIndex = 2
    }
}, label: {
    Text("Tap to move to section 3")
})
```

**Comment by cellininicholas** [comment]
OOH amazing, thank you!
I'm getting animations now, but some inconsistent behaviour in different situations...
![2020-07-05 18 36 29](https://user-images.githubusercontent.com/683377/86528943-08f62900-bef0-11ea-9c80-c4f889974f33.gif)

Could it be that I'm using a `UIViewRepresentable` view as my Pager Content?

**Comment by fermoya** [comment]
@cellininicholas, it’s not that you’re using `UIViewRepresentable`. So `Pager` doesn’t load all pages at once but instead it builds them on demand. So my guess is that, considering the size of those pages and the fact that you have 4 elements, if you’re on index 0 and click on index 1 or 2 it should be fine and you’ll see a scroll effect whereas if you clicked on index 3 you’ll see that “inconsistency” you mention. What’s happening is that item isn’t loaded so the animation isn’t a translation (pagination) but a fade-in.

There’s a variable called `recyclingRatio` in the source code. If you modify it and make that number larger. Can you try and make this and tell me if that solves the issue? I might consider adding a new modifier to switch from _lazy_ to _eager_ mode.

**Comment by fermoya** [comment]
@cellininicholas I've released [v1.8.0-beta.1](https://github.com/fermoya/SwiftUIPager/releases/tag/1.8.0-beta.1) with a new modifier. Could you please tell me if adding `contentLoadingPolicy(.eager)` fixes your issue?

**Comment by cellininicholas** [comment]
That's done it, working well!
Thanks so much!!! :D

**Comment by fermoya** [comment]
@cellininicholas , glad to hear that. I'm close this and schedule a release. I'm gonna see if I can fit some fix in v1.8.0. You can use the beta version in the meantime.

PS: beautiful animation, I love it

**Comment by cellininicholas** [comment]
Thanks! I tweaked the timing curve at the bottom of Pager.swift :)
```
withAnimation(.timingCurve(0.6, 0.6, 0, 1, duration: 0.5)) {
      self.draggingOffset = 0
      self.pageIndex = newPage
      self.draggingStartTime = nil
}
```

**Comment by joshuadiezmo** [comment]
> Hi @cellininicholas, I understand you want to do something like I do in [`ColorsExampleView`](https://github.com/fermoya/SwiftUIPager/blob/master/Example/SwiftUIPagerExample/Examples/ColorsExampleView.swift)? You need to use `withAnimation`:
> 
> ```swift
> // somewhere in your custom view
> @State var pageIndex = 0
> 
> // somewhere in your body
> Pager(page: $pageIndex, ...)
> 
> // somewhere else in your body
> Button(action: {
>     withAnimation {
>         self.pageIndex = 2
>     }
> }, label: {
>     Text("Tap to move to section 3")
> })
> ```

this work. thanks man.

**Comment by VanHoutte** [comment]
Hi

When scrolling through my pages, i use the following animation:
`                        .pagingAnimation { (_) -> PagingAnimation in
                            return .custom(animation: .interactiveSpring())
                    }
`

When I use the following animation to switch between pages:
`
                withAnimation(.interactiveSpring()) {
                    self.currentIndex += 1
                }`

I don't get the same animation, any ideas how to fix this?

**Comment by fermoya** [comment]
@VanHoutte refer to #118 , I think this should be a new thread
