### ISSUE TITLE
[BUG] PagerContent removes all animations for its contents

### ISSUE THREAD

**Issue by frin** [fermoya/SwiftUIPager#82]
**Describe the bug**
When I add an element that has an animation inside the Pager, it will not animate.

**To Reproduce**
Sample code:
```
struct HighlightButtonStyle: ButtonStyle {
    func makeBody(configuration: Configuration) -> some View {
        configuration.label
            .scaleEffect(configuration.isPressed ? 0.95 : 1)
    }
}

struct DemoView: View {
    @State var currentPage: Int = 0
    var items = Array(0..<4)
    
    var body: some View {
        Pager(page: $currentPage, data: items, id: \.self) { index in
            Button(action: {}) {
                ZStack(alignment: .topLeading) {
                    Color.blue
                    
                    VStack(alignment: .leading) {
                        Spacer()
                        
                        Text("Title")
                            .foregroundColor(.white)
                            .font(.system(size: 16, weight: .bold))
                        
                        Text("Subtitle")
                            .foregroundColor(.white)
                            .font(.system(size: 12, weight: .light))
                            .padding(.top, 2)
                    }
                    .padding(10)
                }
                .clipped()
                .foregroundColor(.white)
                .frame(width: 224, height: 317, alignment: .topLeading)
                .cornerRadius(7)
            }
            .shadow(radius: 4)
            .buttonStyle(HighlightButtonStyle())
        }
    }
}
```

**Expected behavior**
Pager should not cancel all animations for its content.

**Environment:**
 - iOS
 - Device: iPhone 11 Pro, simulator, previews
- SwiftUIPager version 1.9.0

**Additional context**
I noticed that the issue is with ".animation(nil)" after opacity in body for PagerContent.swift. If I remove this modifier, the animations inside Pager's content work fine.

**Comment by frin** [comment]
Update: I have found a solution to the problem, I can add .animation(.default) to the button, then it animates correctly.

Perhaps add a note that you must define animation modifier for contents that you want animated.

**Comment by fermoya** [comment]
Hi @frin , if I take your code and comment `Pager` and leave just the button, there's still no animation on stretching. There's though some animation when shrinking back to the previous state, but that's totally unexpected to me as there's no animation added:

![simulator](https://user-images.githubusercontent.com/11335612/88670740-59226e80-d0dd-11ea-9926-11dbc9591455.gif)

My understanding is you need an implicit `.animation(.default)`, see this tutorial [here](https://www.hackingwithswift.com/books/ios-swiftui/customizing-animations-in-swiftui) or at least an explicit `withAnimation` block, see tutorial [here](https://www.hackingwithswift.com/quick-start/swiftui/how-to-create-an-explicit-animation). SwiftUI doesn't animate things by itself.

The line you mention, `animation(nil)` is disabling the animation for `opacity`. See the SwiftUI Apple tutorial, step 5:
> Step 5
> Try turning off animation for the rotation by adding another animation modifier just above the scaleEffect modifier.

<img width="1051" alt="Screenshot 2020-07-28 at 14 26 49" src="https://user-images.githubusercontent.com/11335612/88671637-7277ea80-d0de-11ea-9f4e-6519f171aedd.png">
 
I can't add this to my documentation as this is part of the SwiftUI documentation. What I can do is rename this issue to make it easier to find for other users that find the same problem
