### ISSUE TITLE
[BUG] crash when trying to reload views too quickly

### ISSUE THREAD

**Issue by yyl0** [fermoya/SwiftUIPager#83]
**Describe the bug**

My app crashes during the SizeViewModifier .onReload perform self.size = proxy.size
Logs: "Recorded stack frame" and "enqueued from com.apple.main-thread (Thread 1)"

**To Reproduce**
- Steps to reproduce the behavior
- Sample code

Works fine when I navigate away from a view that has pager and then back SLOWLY, but doing so quickly causes this crash.

```
Pager(page: self.$currentPage, data: Array(0..<self.postArray.count), id: \.self, content: { index in
                        PostView(
                            loading: self.$loading,
                            chosenIndex: self.carouselStartIndex,
                            post: self.postArray[index],
                            nested: self.nested,
                            parent: self,
                            postIndex: index,
                            receivedIndex: self.$currentPage)
                        
                    }) // pager
                        //                        .multiplePagination() // too buggy right now
                        .vertical()
                        .swipeInteractionArea(.page) // or else the post carousel can't be scrolled
                        .onPageChanged { newIndex in
                            if newIndex == 0 { self.counterCheck += 1 } else {
                                self.counterCheck = 0
                            }
                            self.currentPage = newIndex
                            
                            if !self.loadedOnce { self.loadedOnce = true }
                    } // page change`
```

**Expected behavior**

To not crash

**Screenshots / Videos**

<img width="1947" alt="Screen Shot 2020-07-28 at 5 08 00 PM" src="https://user-images.githubusercontent.com/1329425/88741913-a7436c00-d0f5-11ea-8aff-5de90cf2485f.png">

**Environment:**
 - OSX: [e.g. iOS] 13.5.1
 - Device [e.g. iPhone6] iPhone 11 Pro
- SwiftUIPager version 1.9.0-beta.3

**Additional context**

**Comment by fermoya** [comment]
Hi @yyl0 , this issue is duplicated with #60, I gave there an answer. This shouldn’t happen to you in Xcode 12.

In any case, please update to version 1.9.0 (not the beta, the production-ready release) as `SizeViewModifier` disappears in this version.
