### ISSUE TITLE
[FEAT] Callback on Drag Begin to allow you to hide the keyboard like UIKit ScrollView

### ISSUE THREAD

**Issue by soulfoodz** [fermoya/SwiftUIPager#89]
**Is your feature request related to a problem? Please describe.**
I need to resignFirstResponder when drag begins.

**Describe the solution you'd like**
Callback just like -onPageChanged for -onDragBegan

**Describe alternatives you've considered**
This one works

**Additional context**
I can do this and submit a PR if you'd like. I did it in the example project just like you did -onPageChanged, and it works for me.

**Comment by fermoya** [comment]
@soulfoodz if you have it ready, sure! Submit a PR and I’ll accept it. Whatever you have. I’ll then add tests or document it and make a release

**Comment by soulfoodz** [comment]
Cool. Done.

**Comment by fermoya** [comment]
Successfully merged, thanks. I was going to wait for a few days before making the release in case anything else comes up and I can include it. I can release a beta version so that you're updated, would that work for you? Please, let me know your thoughts.

PS: thanks a lot for your contribution

**Comment by soulfoodz** [comment]
That would be awesome. Thanks!
Eric Webbm: 484.602.4929 ericwebb85@yahoo.com 

    On Thursday, August 6, 2020, 03:32:36 AM CDT, Fernando <notifications@github.com> wrote:  
 
 


Successfully merged, thanks. I was going to wait for a few days before making the release in case anything else comes up and I can include it. I can release a beta version so that you're updated, would that work for you? Please, let me know your thoughts.

PS: thanks a lot for your contribution

**Comment by fermoya** [comment]
Hi @soulfoodz , sorry for the late response, I've been working on CI GitHub Actions to automatize the release generation.

Version 1.10.1 is live now (minor for your modifier and patch for the CI jobs)
