### ISSUE TITLE
Implementing NavigationLink

### ISSUE THREAD

**Issue by homanp** [fermoya/SwiftUIPager#9]
Hi there @fermoya , 

Using SwiftUIPager for my project. How can I use NavigationLink with SwiftUIPager, tried the following but couldn't get it to work:

```
NavigationLink(destination: SomeView()) {
    Pager(...)
}
```

Any ideas?

**Comment by fermoya** [comment]
Hi @homanp ,

Yes, indeed. I have a `TapGesture` attached to the unfocused items and this is colliding with your `NavigationLink`.

I've just uploaded a beta version, 1.2.3-beta.1 where I remove this `TapGesture` as I believe doesn't make much sense. It should work now.

There's still an issue that I've noticed and it's that `NavigationLink` might take the hit and kind of "break" if the dragging is not enough to swipe the page. However, from what I've been able to see, this is more a SwiftUI issue. I've seen some issues out there:
* [SwiftUI: NavigationLink and ScrollView drag gesture colliding](https://stackoverflow.com/questions/58440469/swiftui-navigationlink-and-scrollview-drag-gesture-colliding)
* [How to perform an action after NavigationLink is tapped?](https://stackoverflow.com/questions/58897453/how-to-perform-an-action-after-navigationlink-is-tapped)

**Comment by homanp** [comment]
@fermoya cool, I'll try the beta then to see how it works. Thanks for the swift fix.

**Comment by fermoya** [comment]
@homanp the issue I was telling you about you can find [here: NavigationLink Works Only for Once
](https://stackoverflow.com/questions/59279176/navigationlink-works-only-for-once)

I'm just trying on Xcode 13.2 and it's working fine so it must be something related to Xcode 13.3. See with the beta:

![simulator](https://user-images.githubusercontent.com/11335612/73483341-29491700-4397-11ea-9903-18a1a821f18a.gif)

I'm gonna release v1.2.3, hope it helps.

Thanks for opening the issue, I'm gonna keep it open in case you find anything else related.

**Comment by homanp** [comment]
Yeah, I found the same thing. I’ll install the new version and try it out!

Thanks again!

**Comment by fermoya** [comment]
Okay then. You have it live now, 1.2.3. Any other other issue, don't hesitate to reopen.

Thank you
